### ISSUE TITLE
invisible without reserving space

### ISSUE THREAD

**Issue by denjaland** [tailwindcss/discuss#101]
Hi,

Am I missing something, or am I unable to apply a class that will basically "remove" an item from my layout.  I tried using `class="invisible md:visible"` but even though it makes it invisible, it reserves the space.

The whole idea of not having it visible on mobile devices, is to get some much needed space.
I understand from the docs this is wanted behaviour, which is fine, but is there a utility class that allows me to really hide an item?

**Comment by adamwathan** [comment]
You want `hidden` which sets `display: none`. The visibility helpers are just for changing the CSS `visibility` property 👍

**Comment by hacknug** [comment]
Also if you need that content to be accessible to screen reader you could use a helper class like the one described here: https://github.com/tailwindcss/tailwindcss/issues/189

**Comment by denjaland** [comment]
yeah - I found the hidden one.
Thanks for your feedback, guys.
Loving tailwind :)

**Comment by Yarrney** [comment]
I have been having a similar issue with `class="hidden sm:block"`.  It's strange because all the other sm breakpoints work fine, but is appears the `display: none` is overriding `display: block`.  Am I missing something here?

I'm also using this with react so I'm unsure as to whether that may be causing any issues...

**Comment by dimsav** [comment]
I guess we can close this @denjaland

**Comment by denjaland** [comment]
yeah - Closing it now :-)

**Comment by Acidic9** [comment]
I don't find `.hidden` in any of the documentation.

**Comment by adamwathan** [comment]
It’s not super obvious unless you have enough CSS experience to know that
you need to set display: none, but it’s here:

https://tailwindcss.com/docs/display

Will be continuing to improve the docs over the next few weeks 👍🏻

**Comment by Acidic9** [comment]
Ah i was looking for display none there before but i must've been keeping my eye out for a class called 'none'
