### ISSUE TITLE
Access CSS Styles as objects

### ISSUE THREAD

**Issue by roarkmccolgan** [tailwindcss/discuss#103]
Hi All,

This could be a stupid question but would help me in my current situation.
Would it be possible to access underlying styles from tailwind?
An example would be:

```
import tailWind from 'tailwindcss';
window.tailWind = tailWind

//later on in the app somewhere:

var marginRight4 = tailWind.mr-4;
console.log(marginRight4);

// 'margin-right: 1rem;'
```

**Comment by m1guelpf** [comment]
@roarkmccolgan You can
``` javascript
let defaultConfig = require('tailwindcss/defaultConfig')()
```

**Comment by adamwathan** [comment]
To be clear, you can import your config file which will give you access to all of your values, and then you can access those values and use them as needed, like this:

```js
let tailwind = require('/tailwind.js') // Assuming you've created your own config file

console.log(tailwind.margin[4]) // '1rem'
```

You'd have to build the actual style properties yourself from those values.

**Comment by jferrettiboke** [comment]
> You'd have to build the actual style properties yourself from those values.

It would be nice if Tailwind could provide a way to get all the style properties from CSS classes. It would be very useful for CSS-in-JS.

Instead of this:

```js
const tailwind = require('./tailwind');

const styles = {
  marginTop: tailwind.margin[4],
  marginBottom: tailwind.margin[4]
};

/*
{
  marginTop: '1rem',
}
*/
```

This:

```js
const myTailwindConfig = require('./tailwind');
const { getStylesFromClasses } = require('tailwind')(myTailwindConfig);

const styles = getStylesFromClasses('my-4');
```

**Comment by jferrettiboke** [comment]
> You'd have to build the actual style properties yourself from those values.

It would be nice if Tailwind could provide a way to get all the style properties from CSS classes. It would be very useful for CSS-in-JS.

Instead of this:

```js
const tailwind = require('./tailwind');

const styles = {
  marginTop: tailwind.margin[4],
  marginBottom: tailwind.margin[4]
};

/*
{
  marginBottom: '1rem',
  marginTop: '1rem',
}
*/
```

This:

```js
const myTailwindConfig = require('./tailwind');
const { getStylesFromClasses } = require('tailwind')(myTailwindConfig);

const styles = getStylesFromClasses('my-4');

/*
{
  marginBottom: '1rem',
  marginTop: '1rem',
}
*/
```

**Comment by roarkmccolgan** [comment]
![image](https://user-images.githubusercontent.com/1567162/35174674-ec6e5446-fd78-11e7-8857-e0517e8759c7.png)

@adamwathan Damn you're good
