### ISSUE TITLE
Stretching sidebar vertically

### ISSUE THREAD

**Issue by Jeroen-G** [tailwindcss/discuss#106]
So, I have two pages on codepen:

[Page A](https://codepen.io/jeroeng/pen/Rxmymg)
[Page B](https://codepen.io/jeroeng/pen/jYovYx)

But I can't get the sidebar to work in such a way that it stretches for the full length of the page in both examples, dragging the footer down with it. The moment I get it working in B, it screws up A. I hope someone could take a look at the code and have a _eureka_ moment to help me out!

**Comment by adamwathan** [comment]
Here you go :)

https://codepen.io/adamwathan/pen/JMqaxY

Trick is adding `min-h-screen` to the wrapper to force it to full height, then making the second column a flex container in the column direction and allowing the middle section to `flex-grow`.

Simplified:

```html
<div class="flex min-h-screen">
    <!-- Sidebar -->
    <div><!-- ... --></div>

    <!-- Main area -->
    <div class="flex flex-col">
        <!-- Header area -->
        <div><!-- ... --></div>

        <!-- Content area -->
        <div class="flex-grow"><!-- ... --></div>

        <!-- Footer area -->
        <div><!-- ... --></div>
    </div>
</div>
```

**Comment by Jeroen-G** [comment]
Yaaay, thanks a lot for the (very quick) response! 👍
