### ISSUE TITLE
Unable to create a config file.

### ISSUE THREAD

**Issue by uployd** [tailwindcss/discuss#107]
I am excited to use this Tailwind CSS, but I am not able to create a config file following instructions in websites installation. When I try to run 'tailwind init tailwind-config.js' in my project's root folder, I gives me a syntax error. Attaching screenshot here. 
![capture](https://user-images.githubusercontent.com/12412659/35386089-b81dc010-01f0-11e8-8d07-7470d3e2d4e6.PNG)

**Comment by adamwathan** [comment]
Which version of Node are you using? I would try upgrading to the latest version if yours is a bit outdated and seeing if that helps 👍

**Comment by uployd** [comment]
Hi Adam, thanks for such a quick response. I am currently using 4.2.6. I will upgrade and try again. By the way, this is a syntax error which it shows in the logs. Isn't there a problem with cli.js ? Probably a typo? I looked into the file, but didn't find any though.

**Comment by adamwathan** [comment]
It's a syntax error on 4.2.6 yeah, but we target Node 6.9.0 and up, which supports all the syntax used in that file.

You can see here that Node didn't support default function parameters until version 6:

http://node.green/#ES2015-syntax-default-function-parameters

**Comment by uployd** [comment]
Alright. Thank you Adam. It's successfully working for me now, I updated node to latest. That information was helpful. :) 👍
