### ISSUE TITLE
3rd party styles

### ISSUE THREAD

**Issue by illycz** [tailwindcss/discuss#108]
Best practices for include styles of libraries like slider etc.?

When I import it between preflight and utilities postcss-import get this warning:
```
@import must precede all other statements (besides @charset)
```

What do you think?

**Comment by psren** [comment]
To solve this problem you could use SASS or Less for ```@import```.
postcss-import handles imports a bit different and comes with the error above.

There are comments in the base-css file got that.

```css
/**
 * This injects Tailwind's base styles, which is a combination of
 * Normalize.css and some additional base styles.
 *
 * You can see the styles here:
 * https://github.com/tailwindcss/tailwindcss/blob/master/css/preflight.css
 *
 * If using `postcss-import`, you should import this line from it's own file:
 *
 * @import "./tailwind-preflight.css";
 *
 * See: https://github.com/tailwindcss/tailwindcss/issues/53#issuecomment-341413622
 */
@tailwind preflight;
```

Notice the

> If using `postcss-import`, you should import this line from it's own file:

**Comment by illycz** [comment]
I also think about cascade and specificity...

**Comment by psren** [comment]
@illycz you don't have any difference there if you follow the advice.

The order of CSS is the same.
You just have to make a new file "preflight.css".

```css
/* preflight.css */
@tailwind preflight;
```

```css
/* main.css */
@import preflight.css;
@import custom-utilities.css;

/** ..... */
```

If you don't like that approach (I don't) you could also mark utilities as important.

**Comment by adamwathan** [comment]
Like @psren mentioned and like the example CSS file suggests, if you are using postcss-import you need to put the two `@tailwind` calls in their own files. postcss-import is very strict about the CSS spec which says that `@import` statements have to come before any other statements in your file.

Here's an example project to make it as clear as possible:

https://github.com/adamwathan/tailwind-postcss-import-demo/blob/master/src/styles.css

There are no declaration order or specificity concerns to worry about.

**Comment by illycz** [comment]
Yes I understand suggestions for postcss-import. Thanks for clarification and demo repo.

But second question is about best practices for implement 3rd libraries code (they often uses nested selectors etc.) What is your opinion for specificity battle :) and where (I mean order) you import those files.

Thanks

**Comment by psren** [comment]
I always ```!import``` all utilities :-D

https://css-tricks.com/when-using-important-is-the-right-choice/
https://csswizardry.com/2016/05/the-importance-of-important/

So I don't have this issues at all :-)

**Comment by jferrettiboke** [comment]
If everything is very important, then nothing is important. Think about that deeply.

**Comment by jferrettiboke** [comment]
> I always !import all utilities :-D

@psren If everything is very important, then nothing is important. Think about that deeply.

**Comment by illycz** [comment]
When I try to use Tailwind with Blendid: https://github.com/vigetlabs/blendid I get `@apply cannot be used with .pt4 because .pt4 either cannot be found, or it's actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that .pt4 exists, make sure that any @import statements are being properly processed *before* Tailwind CSS sees your CSS, as @apply can only be used for classes in the same CSS tree.`

With this main file:
```
@import "./tailwind-preflight.css";
@import "./typography.css";
@import "./tailwind-utilities.css";
```

and also with this (without @import):
```
@tailwind preflight;
body {
  @apply .pt4;
}
@tailwind utilities;
```

Part of my config:
```
const plugins = [
    require("postcss-import"),
    require("tailwindcss")(process.env.INIT_CWD + "/tailwind.js"),
    require("postcss-cssnext")
];

return gulp
    .src(paths.src)
    .pipe(gulpif(!global.production, sourcemaps.init()))
    .pipe(postcss(plugins))
    .pipe(gulpif(global.production, cssnano(cssnanoConfig)))
    .pipe(gulpif(!global.production, sourcemaps.write()))
    .pipe(gulp.dest(paths.dest))
    .pipe(browserSync.stream());
```

**Comment by illycz** [comment]
@reinink for me !Important make sense for utilities but not in functional CSS where everything is utility...

**Comment by adamwathan** [comment]
@illycz The error is correct, `.pt4` doesn't exist. The class is `.pt-4`.

**Comment by illycz** [comment]
@adamwathan 

https://media3.giphy.com/media/bjfv14wZU7PiM/giphy.gif

Sorry :)

**Comment by psren** [comment]
>> I always !import all utilities :-D

> @psren If everything is very important, then nothing is important. Think about that deeply.

@jferrettiboke it's also important that things do what their name tells you :-)
In case of utilities you should not be able to overwrite them, and instead adjust the classes in your HTML.

```css
.foo > div {
    margin-top: 0;
}
```

```html
<div class="foo">
    <div id="yolo" class="mt-3"></div>
</div>
```

imo ```#yolo``` should have a top-margin and not ```0```.
If it should have ```margin-top: 0``` just remove the utility itself.

I use the approach with ```!important``` in legacy projects where overall specitivity is very high.

But thats's a bit too much offtopic :-)

**Comment by illycz** [comment]
@psren yes thats what I meant when I talked about difference between utilities and functional CSS like a system...
