### ISSUE TITLE
Ordering Flex Items

### ISSUE THREAD

**Issue by rkawajan** [tailwindcss/discuss#116]
Hey,
I would like to know any plan for "Ordering Flex Items"?

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordering_Flex_Items

**Comment by hacknug** [comment]
Was discussed here: https://github.com/tailwindcss/tailwindcss/issues/52

**Comment by adevade** [comment]
I just released a plugin for Tailwind 0.5+ to add this! 
It's available on [npm](https://www.npmjs.com/package/tailwindcss-flexbox-order) and [GitHub](https://github.com/035media/tailwindcss-flexbox-order).

The plugin adds `.order-#` (and `.-order-#` for negative numbers) classes.

**Comment by joshmanders** [comment]
Can you add that to https://github.com/merchedhq/awesome-tailwindcss @adevade

**Comment by adevade** [comment]
@joshmanders Done!
