### ISSUE TITLE
A question about repeated utilities

### ISSUE THREAD

**Issue by nitinja** [tailwindcss/discuss#117]
Hi People,

Tailwind looks great so far! A noob question here.

I have a default configuration. In final output file, I am wondering why we have repeated classes for something like, say 

```
.bg-transparent {
  background-color: transparent;
}
```

for each of the screen sizes, we again have a class like

```
  .sm\:bg-transparent {
    background-color: transparent;
  }
 .lg\:bg-transparent {
    background-color: transparent;
  }
  .xl\:bg-transparent {
    background-color: transparent;
  }
```
Here, background-colour: transparent; will remain same no matter the screen size. so what is the purpose of differentiating them these on screen sizes?

**Comment by taylorbryant** [comment]
I'm not entirely sure what you're asking here. 🤔 

* `.bg-transparent` essentially says "make the background transparent for 1px screen width and up"
* `.sm:bg-transparent` applies the rule for 576px and up
* `.md:bg-transparent` applies the rule for 768px and up
* `.lg:bg-transparent` applies the rule for 992px and up
* `.xl:bg-transparent` applies the rule for 1200px and up

You can, of course, customize the breakpoint values in your Tailwind config file (named `tailwind.js` by default).

For a quick example of changing the background color on different breakpoints, see the interactive example under **Responsive example** on this page: https://tailwindcss.com/docs/responsive-design.
