### ISSUE TITLE
Struggling to get a responsive grid working

### ISSUE THREAD

**Issue by stevieg83** [tailwindcss/discuss#123]
Noticing that my output CSS is producing classes like

```
.sm\:w-1\/2 {
    width: 50%;
  }
```

rather than `sm:w-1/2 md:w-1/3 lg:w-1/4 xl:w-1/6` 

Not sure if it's because I'm using LESS?

Laravel Mix config is pretty basic

```
let mix = require('laravel-mix');
let tailwindcss = require('tailwindcss');

mix.less('./src/css/ashkirk.less', 'public/css')
	.options({
		postCss: [
			tailwindcss('./tailwind.js'),
		]
	})
	.js('./src/js/ashkirk.js', 'public/js');
```

with a default TW config (other than a colour customisation).

**Comment by adamwathan** [comment]
That’s correct, special characters needs to be escaped in CSS to be used in
HTML. Copy and paste one of our grid examples into your own project and
things should work just fine.

**Comment by stevieg83** [comment]
Thanks for the prompt response @adamwathan I was missing `flex-wrap` on the container 🤦🏻‍♂️
