### ISSUE TITLE
color #000 is missing in the default color palette

### ISSUE THREAD

**Issue by marekzelinka** [tailwindcss/discuss#125]
Hello, why isn't there a pure black ```#000000``` color in the [default color palette](https://tailwindcss.com/docs/colors#default-color-palette)? Is this intentional?

Thanks!

**Comment by adamwathan** [comment]
Yeah that's intentional; there's not really enough situations where you would use real black in web design to warrant including it by default.

Here's a great article about not using black in design that might be interesting:

https://ianstormtaylor.com/design-tip-never-use-black/

**Comment by marekzelinka** [comment]
ok thanks, it is good that tailwind is configurable 😃.
here is a great article to understand why I was asking https://www.wired.com/2016/10/how-the-web-became-unreadable/

**Comment by tlgreg** [comment]
Yeah, color palette is encouraged to be changed anyway. :slightly_smiling_face:

Just a note to this that contrast accessibility with tailwind's *black* is not bad at all, its still in the advised contrast range even with grey (8.2:1) and even in the minimum with grey-dark (4.8:1).

*WCAG advised for body text is 7:1 and minimum is 4.5:1.*
