### ISSUE TITLE
[enhancement] Support for custom class

### ISSUE THREAD

**Issue by maki10** [tailwindcss/discuss#14]
Hi is it possible to add support for custom class for less or sass?

Something like this?

```html
<div class="image-wrapper">
    <img src="...">
</div>
```

```less
.image-wrapper {
    .pin-l
    .block
    .visible
    .z-10
}
```

**Comment by reinink** [comment]
This is [possible with Tailwind](https://tailwindcss.com/docs/extracting-components) (which is why I'm assuming learned since you closed it), but for the  benefit of others:

```css
.image-wrapper {
  @apply .pin-l .block .visible .z-10;
}
```

**Comment by maki10** [comment]
@reinink It's closed by accident. That is great feature.

**Comment by reinink** [comment]
Awesome, I'm going to close this again then. Hit us up if you have any other issues! :feelsgood:
