### ISSUE TITLE
having trouble getting .container plugin working

### ISSUE THREAD

**Issue by davidmathlogic** [tailwindcss/discuss#140]
I'm using the latest version of Tailwind for the first time, and the generated CSS doesn't have the .container class in it anywhere. This is using the default config with the .container plugin enabled (see below). 
![image](https://user-images.githubusercontent.com/18088182/38511512-6bdc13ec-3bf6-11e8-9e35-3ca447cd280e.png)
Any idea what I'm doing wrong?

**Comment by davidmathlogic** [comment]
That was fast! And you're exactly right. Thanks!

**Comment by adamwathan** [comment]
No prob! 😄
