### ISSUE TITLE
Support more variants?

### ISSUE THREAD

**Issue by joshmanders** [tailwindcss/discuss#149]
I am doing my best to not have to have a CSS file ever in my projects again, but I ran into something tonight while styling a button... Apparently when you set background colors, etc on a button, `disabled` no longer changes the visual styling... It'd be nice if we could have `bg-blue hover:bg-blue-dark disabled:bg-blue-light` to support when the button or input or whatever is disabled.

**Comment by adamwathan** [comment]
Some discussion here:

https://github.com/tailwindcss/tailwindcss/issues/136#issuecomment-349012893

Ultimately I'd like to make it possible to create new variants through the plugin system, but haven't had a chance to dig into that yet.
