### ISSUE TITLE
How to have multiple color schemes/themes like light and dark theme?

### ISSUE THREAD

**Issue by exwizzard** [tailwindcss/discuss#153]
I would like to have a light and dark theme on my website and switch between them but I am not sure how to do this with tailwind. Do I need to create 2 config files and 2 css files?

**Comment by hacknug** [comment]
I'd just create color classes like usual and use `@apply` to create a couple aliases like `.text-light` and `.text-dark` (same thing for background classes). The use this alias classes on your doc and swap them when switching themes using a button or something like that.

**Comment by codeitlikemiley** [comment]
this is more on javascript, if ur using vue js
u can use dynamic class 
```html
<p :class="{'text-light': isLightTheme, 'text-dark': isDarkTheme}"></p>
```
then in your data
```js
data: () => ({
    dark: false
}),
computed: {
 isLightTheme(){
return this.dark === false
},
isDarkTheme(){
return this.dark === true
}
```

**Comment by LoganDark** [comment]
or you can just put a `.light-theme` or `.dark-theme` class on `body` instead of having computed properties for every element on the page @codeitlikemiley

**Comment by vinayakkulkarni** [comment]
This might be a really helpful thing if anyone can come up with a viable solution for this.

**Comment by MpMeetPatel** [comment]
we can use local scoped css variables for different theme colors(we don't need to change utilities likes spacing,borders etc).

most of the time people want dark/light theme. we can make one 2 different wrapper class with only containing css variables in it and generate CSS from it. Below Demo is an perfect example of it. 

https://github.com/adamwathan/theming-tailwind-demo

**Comment by exwizzard** [comment]
@MpMeetPatel That is what I ended up using once it came out

**Comment by fpauser** [comment]
Sadly using css variables is not an option when IE support is a requirement.
