### ISSUE TITLE
Recommended way to use loops and mixins

### ISSUE THREAD

**Issue by natemate90** [tailwindcss/discuss#158]
What is the recommended way to use a loop for custom classes, i.e. to loop through sizes in order to generate different versions?
I want to achieve the following:
```
	.move-u-1 {
		transform: translateY(-1px);
	}

```
and generate these classes in different versions

or for example create a mixin similar as in Sass:
```
	.move-fast {
		transition: all 0.1s;
		-moz-transition: all 0.1s;
		-webkit-transition: all 0.1s;
		-o-transition: all 0.1s;

	}

``` 

Thanks for your help!

**Comment by hacknug** [comment]
If you only wanna add vendor prefixes, you should take a look at [autoprefixer](https://github.com/postcss/autoprefixer). Doing this manually is never a good idea.

**Comment by adamwathan** [comment]
Hi @natemate90!

> What is the recommended way to use a loop for custom classes, i.e. to loop through sizes in order to generate different versions?

I would use Tailwind's [plugin system](https://tailwindcss.com/docs/plugins#adding-utilities) for this. You can accept the values you want to generate as configuration parameters from the user and use that information to generate all those classes in JS.

> or for example create a mixin similar as in Sass

You can use the [`@apply`](https://tailwindcss.com/docs/functions-and-directives#apply) directive to mix existing utilities into other classes. I would make a class like `.move-fast` like you included in your original post, and mix that into other classes like this:

```css
.foo {
  @apply move-fast;
}
```

**Comment by natemate90** [comment]
Thanks both for your replies!
Only today I just figured out that autoprefixer must have been working all the time already when importing custom css just before @tailwind utilities! 😄
