### ISSUE TITLE
I can't get it to work, tailwind with gulp and sass!

### ISSUE THREAD

**Issue by peimn** [tailwindcss/discuss#160]
Here is my gulpfile:
```js
gulp.task('sass', function (done) {
        gulp.src([
            './sass/main.scss'
        ])
            .pipe(sass({outputStyle: 'compressed'}).on('error', sass.logError))
            .pipe(postcss([atImport(), tailwindcss('./tailwind.js'), require('autoprefixer')]), {syntax: require('postcss-scss')})
            .pipe(cleanCSS())
            .pipe(stripCssComments({preserve: false}))
            .pipe(rename({
                suffix: ''
            }))
            .pipe(gulp.dest('./dist/css'));
        done();
    });
```

and my main.scss:
```scss

@tailwind preflight;
@tailwind components;

@import "core/fonts";
@import "core/mixins";
@import "core/variables";
@import "core/animation";
@import "node_modules/bootstrap-sass/assets/stylesheets/bootstrap";

@tailwind utilities;

@import "fonts";
```

when I run sass task I get this error:
`@apply` cannot be used with `.my-sm` because `.my-sm` either cannot be found, or it's actual...

I searched and read all the suggestions about this error but can't get it to work!
What is wrong with my gulpfile?

**Comment by adamwathan** [comment]
It's probably because of using the `atImport()` plugin while using the `@tailwind` syntax.

Try writing your CSS this way:

```css
@import "tailwindcss/preflight";
@import "tailwindcss/components";

@import "core/fonts";
@import "core/mixins";
@import "core/variables";
@import "core/animation";
@import "node_modules/bootstrap-sass/assets/stylesheets/bootstrap";

@import "tailwindcss/utilities";

@import "fonts";
```

That might also act weird because I would expect Sass should be processing all your imports, so if that's the case consider just removing the `atImport` plugin and letting Sass take care of the imports.

**Comment by peimn** [comment]
Hi thank you Adam,

ok I did that but not succeed:

first try:
error -> tailwindcss/preflight not found

second try: I created 3 files (preflight.scss, ...) and put `@tailwind`s there
error-> same:
@apply cannot be used with .my-sm because .my-sm either cannot be found, or it's actual...
