### ISSUE TITLE
Tailwind color percentages for tints & shades

### ISSUE THREAD

**Issue by aaronmoodie** [tailwindcss/discuss#164]
Is Tailwind was using a set percentage for the tints and shades in the default colour pallet? if so, would you be able to provide them so we're able to accurately match new colors to the `-light`, `-lighter` and `-lightest` (and dark alt) values. 

Thanks.

**Comment by adamwathan** [comment]
Hey @aaronmoodie! We actually picked all those colors by eye, I was hoping we could math the shit out of it somehow but turns out color is really complicated and the only way we've found to get good results so far is matching colors across the palette manually.

**Comment by aaronmoodie** [comment]
Gotcha. Thanks @adamwathan.

**Comment by hacknug** [comment]
Just for reference in case anyone wants to tackle this at some point, here's a website I've used in the past when trying to do this exact same thing: http://razorltd.github.io/sasscolourfunctioncalculator/
