### ISSUE TITLE
how to enable all the modules

### ISSUE THREAD

**Issue by rooney1989315** [tailwindcss/discuss#166]
is there a way to enable all features under modules?
```
modules: {
    appearance: ['responsive'],
    backgroundAttachment: ['responsive'],
    backgroundColors: ['responsive', 'hover'],
    backgroundPosition: ['responsive'],
    backgroundRepeat: ['responsive'],
    // ...
  },
```
Can not find this in the Docs

**Comment by hacknug** [comment]
You can just set modules to `'all'` and it will generate classes for all variants:
https://github.com/tailwindcss/tailwindcss/blob/7a0a0a8bd7d0ead66cd95d9e307d01c778a5e842/__tests__/mergeConfigWithDefaults.test.js#L56

**Comment by tlgreg** [comment]
You should expect a very large css file and long compilation.
btw it is indeed undocumented.

**Comment by rooney1989315** [comment]
@hacknug Wooo, thank you, it's really good to know.

**Comment by rooney1989315** [comment]
@tlgreg yes I know, it's going to be very very big, I just want to play around with it. It's not going to be in the production lol
