### ISSUE TITLE
How to add a font-family from Google Fonts

### ISSUE THREAD

**Issue by wishinghand** [tailwindcss/discuss#177]
I looked in the Tailwind docs: https://tailwindcss.com/docs/fonts#font-families and it seems like it should be as easy as adding a name to the fonts list. I didn't recognize some of the font-families (Oxygen, Cantarell, Segoe UI) but they all seem to be Google fonts. I'd like to add 'Nunito' to the sans list but whenever I add to to the beginning on the list and re-run `npm run dev` none of the sans-serif fonts change. Am I'm mistaken in how to do this? I'm not sure if the Tailwind package automatically downloads the files from Google fonts or how the existing families are packaged.

**Comment by adamwathan** [comment]
Tailwind doesn't do anything special to auto-import fonts or anything, so you need to import them the same way you would in a regular project, either by adding the Google stylesheet reference to the top of your HTML like this:

`<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">`

...or by importing your fonts with `@font-face` declarations at the beginning of your CSS file:

```
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'), url(https://fonts.gstatic.com/s/roboto/v18/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}
```

Hope that helps!

**Comment by wishinghand** [comment]
Would it make sense to put that import in `@components` then?

**Comment by mandaputtra** [comment]
yes you can, but first you must provide the appropriate font.
