### ISSUE TITLE
Print Styles constrained by container class

### ISSUE THREAD

**Issue by skinnyvin** [tailwindcss/discuss#183]
I have added a 'print' screen using 'raw' as per the docs and this works great for hiding content and defining print styles.

However, I have hit a snag, if the content is within an element that uses the .container class, the resulting print is constrained to the width of the container and I cannot find a way to allow print to override this. This results in A4 prints only being about 50-60% of the page width.

I am likely missing something though?

Thank you

**Comment by skinnyvin** [comment]
I've added this for now which sorts it:

`    @media print {
    .container {
       width:100%;
       max-width: 100%;
    }`

**Comment by adamwathan** [comment]
Does it help if you add `print:max-w-full` to the elements that have the container class? I would expect that to work to override those styles.
