### ISSUE TITLE
Override merge existing lib generators

### ISSUE THREAD

**Issue by naumanjkhan** [tailwindcss/discuss#185]
@adamwathan @reinink @davidhemphill 

I am using tailwind via an npm. Its a great tool. Is there a way to override or combine/merge the existing generators in the lib of this module with custom defined styles.

Consider the following 
```
static: { position: 'static' },
fixed: { position: 'fixed' },
absolute: { position: 'absolute' },
relative: { position: 'relative' },
sticky: { position: 'sticky' },
'pin-none': {
  top: 'auto',
  right: 'auto',
  bottom: 'auto',
  left: 'auto'
},
pin: {
  top: 0,
  right: 0,
  bottom: 0,
  left: 0
},
'pin-y': { top: 0, bottom: 0 },
'pin-x': { right: 0, left: 0 },
'pin-t': { top: 0 },
'pin-r': { right: 0 },
'pin-b': { bottom: 0 },
'pin-l': { left: 0 }
```

This is taken from the position.js. What if I want to add couple of extra classes for position as 
```
'pin-t-m': { top: '50%' },
'pin-l-m': { left: '50%' }
```
and the final output should be 
```
static: { position: 'static' },
fixed: { position: 'fixed' },
absolute: { position: 'absolute' },
relative: { position: 'relative' },
sticky: { position: 'sticky' },
'pin-none': {
  top: 'auto',
  right: 'auto',
  bottom: 'auto',
  left: 'auto'
},
pin: {
  top: 0,
  right: 0,
  bottom: 0,
  left: 0
},
'pin-y': { top: 0, bottom: 0 },
'pin-x': { right: 0, left: 0 },
'pin-t': { top: 0 },
'pin-r': { right: 0 },
'pin-b': { bottom: 0 },
'pin-l': { left: 0 },
'pin-t-m': { bottom: '50%' },
'pin-l-m': { left: '50%' }
```
How can I achieve that.

I know that I can simply define these classes in a separate file but want to keep it as a part of build process, so that I don't have to worry about adding these separately all the times.

**Comment by adamwathan** [comment]
Yep I would suggest creating your own plugin. All of those classes live in our `position` module, so you could [disable that module](https://tailwindcss.com/docs/positioning#disabling) in your config and instead use your own advanced positioning plugin.

Writing plugins is really easy, can read more about it here:

https://tailwindcss.com/docs/plugins

**Comment by naumanjkhan** [comment]
Thank you for the reply. From above I can conclude that there is no way to merge existing modules with your own classes for that module. Either you create a new plugin for extra classes or disable that module and create new plugin will the classes + your new classes for that module.
