### ISSUE TITLE
Minified size is big

### ISSUE THREAD

**Issue by rap2hpoutre** [tailwindcss/discuss#19]
I don't know what could be done about this issue, but the framework is heavyweight, even minified, in comparison with other frameworks (including similar ones like tachyons). Still I already really appreciate your work, and I'm sure I will soon fall in love with this framework. Do you have any plan to optimize it?

**Comment by rap2hpoutre** [comment]
(I opened this issue because I think weight IS actually an argument for users in using a CSS framework)

**Comment by adamwathan** [comment]
Hey @rap2hpoutre! See my response here:

https://github.com/tailwindcss/discuss/issues/18#issuecomment-341572814

**Comment by rap2hpoutre** [comment]
Thanks! Really good answer!
