### ISSUE TITLE
Tailwind opposite of hidden

### ISSUE THREAD

**Issue by larsjanssen6** [tailwindcss/discuss#190]
Hi,

I want an element to be ```hidden``` when it's `sm` but when it's `md` it should be visible. 

```
<div class="sm:hidden md:visible">
     // my content
</div>
```

But that's not working? How could I do this?

**Comment by stephensamra** [comment]
As far as i know the hidden class sets the element to `display: none` so you could set it to any other display property like `block` or `flex`.

**Comment by larsjanssen6** [comment]
@stephensamra thanks!
