### ISSUE TITLE
Is there a way to make the center section to scroll only?

### ISSUE THREAD

**Issue by Olow304** [tailwindcss/discuss#194]
I want to make this center section scroll while keeping the header and the two sidebar stick.

Here is my dashboard image. I only want the middle section to scroll.

![note](https://user-images.githubusercontent.com/7048571/48316050-1983be00-e5ac-11e8-8ee5-a78953b56b91.JPG)

Here is when I scroll up..
![note2](https://user-images.githubusercontent.com/7048571/48316064-3cae6d80-e5ac-11e8-90b4-450dea79cf32.JPG)

@adamwathan

**Comment by adamwathan** [comment]
Here you go:

https://jsfiddle.net/adamwathan/t6h98or0/4/

**Comment by Olow304** [comment]
Thank you adam. Quick question,
