### ISSUE TITLE
Add outline-<color>

### ISSUE THREAD

**Issue by agm1984** [tailwindcss/discuss#196]
I  would like to have Tailwind support changing of outline color, which is the CSS attribute `outline-color`.

I am currently using a workaround which is:

``` css
button:focus {
    outline-color: #ee3150;
}
```

But I would like to be able to do:

``` css
button:focus {
    @apply .outline-pink;
}
```

I don't like how the colour must be manually set because if the colour is ever changed in Tailwind.js config file, then the person must know to grep the code for `#ee3150`.

I propose this not only because it appears to be a good idea for me, but it also appears to be a good idea to fully support a11y by allowing people to use focus/hover/active states that are not just `outline-none`.

I might be able to submit a PR if I could be guided with some approximate instructions because I can't dedicate a lot of time to such a task. My workaround solution works, but I don't love it.

Thanks,
Adam

**Comment by adamwathan** [comment]
Hey Adam! An easy way to add outline styles to your own Tailwind projects would be to write a plugin:

https://tailwindcss.com/docs/plugins#adding-utilities

Then you can use `@apply` to mix it into your other classes just like you've shown in your example 👍🏻

**Comment by agm1984** [comment]
That's beautiful. Thanks for the quick aid and for helping us connect these keywords into Google.

**Comment by agm1984** [comment]
But I do still feel that `outline-color` is a candidate for fostering a11y. I might argue it is a common appearance-related thing, but that's just for the Tailwind crew to chew on.

**Comment by hacknug** [comment]
Is the outline color you wanna use the same as the text color? If so you could simply write `outline-color: currentColor;`.

If that's not the case, couldn't you simple do something like `outline-color: config('colors.pink');`? This is probably closer to what you said you wanted to accomplish and will provide you with more flexibility than using `currentColor`.

**Comment by agm1984** [comment]
The colour is the same as our primary colour, so something like `outline-primary` is all I am after, but my goal was to try to get `outline` to work like `bg`, `text`, or `border`, so I could put any colour like `outline-pink` or `outline-brown` without fiddling with anything.

Your mention there is cool, but I don't want it determining the colour based on upstream markup.

Here is the solution that works fine:

``` javascript
  plugins: [
    require('tailwindcss/plugins/container')({
      // center: true,
      // padding: '1rem',
    }),

    ({ addUtilities }) => addUtilities({
      '.outline-pink': {
        outlineColor: colors.pink,
      },
    }),
  ],
```

The fact that `colors` is available in there is really all I need.

**Comment by thorsteneckel** [comment]
Sorry for posting to old issues but I stumbled over this via Google and build a little (inline) plugin to provide those in my current project. It dynamically generates utility classes for all available colors and variations (e.g. `outline-black` and `outline-green-700`). 

```js
module.exports = {
  theme: {
    extend: {}
  },
  variants: {},
  plugins: [
    function({ addUtilities, theme, config }) {

      let newUtilities      = {};
      const boxShadowPrefix = '0 0 0 3px';
      const colors          = theme('colors');
      Object.keys( colors ).forEach(color => {

        const colorData = colors[color];
        if(typeof colorData === 'string') {
          newUtilities[`.outline-${color}`] = {
            boxShadow: `${boxShadowPrefix} ${colorData}`,
          }
        }
        else {
          Object.keys(colorData).forEach(colorVariation => {
            newUtilities[`.outline-${color}-${colorVariation}`] = {
              boxShadow: `${boxShadowPrefix} ${colorData[colorVariation]}`,
            }
          });
        }
      });
      addUtilities(newUtilities);
    }
  ]
}
```

**Comment by julianaubrey** [comment]
> Sorry for posting to old issues but I stumbled over this via Google and build a little (inline) plugin to provide those in my current project. It dynamically generates utility classes for all available colors and variations (e.g. `outline-black` and `outline-green-700`).
> 
> ```js
> module.exports = {
>   theme: {
>     extend: {}
>   },
>   variants: {},
>   plugins: [
>     function({ addUtilities, theme, config }) {
> 
>       let newUtilities      = {};
>       const boxShadowPrefix = '0 0 0 3px';
>       const colors          = theme('colors');
>       Object.keys( colors ).forEach(color => {
> 
>         const colorData = colors[color];
>         if(typeof colorData === 'string') {
>           newUtilities[`.outline-${color}`] = {
>             boxShadow: `${boxShadowPrefix} ${colorData}`,
>           }
>         }
>         else {
>           Object.keys(colorData).forEach(colorVariation => {
>             newUtilities[`.outline-${color}-${colorVariation}`] = {
>               boxShadow: `${boxShadowPrefix} ${colorData[colorVariation]}`,
>             }
>           });
>         }
>       });
>       addUtilities(newUtilities);
>     }
>   ]
> }
> ```

How do you use this with the focus selector?

**Comment by agm1984** [comment]
That's a good question. I recommend starting a new issue thread quoting that example code. Dr. Wathan might not get notifications effectively in this closed thread.

Additionally, I recommend providing a URL to that new thread in here, so that others in the future could benefit from it.

**Comment by julianalonzo** [comment]
> > Sorry for posting to old issues but I stumbled over this via Google and build a little (inline) plugin to provide those in my current project. It dynamically generates utility classes for all available colors and variations (e.g. `outline-black` and `outline-green-700`).
> > ```js
> > module.exports = {
> >   theme: {
> >     extend: {}
> >   },
> >   variants: {},
> >   plugins: [
> >     function({ addUtilities, theme, config }) {
> > 
> >       let newUtilities      = {};
> >       const boxShadowPrefix = '0 0 0 3px';
> >       const colors          = theme('colors');
> >       Object.keys( colors ).forEach(color => {
> > 
> >         const colorData = colors[color];
> >         if(typeof colorData === 'string') {
> >           newUtilities[`.outline-${color}`] = {
> >             boxShadow: `${boxShadowPrefix} ${colorData}`,
> >           }
> >         }
> >         else {
> >           Object.keys(colorData).forEach(colorVariation => {
> >             newUtilities[`.outline-${color}-${colorVariation}`] = {
> >               boxShadow: `${boxShadowPrefix} ${colorData[colorVariation]}`,
> >             }
> >           });
> >         }
> >       });
> >       addUtilities(newUtilities);
> >     }
> >   ]
> > }
> > ```
> 
> How do you use this with the focus selector?

It turns out that I only had to specify the **focus** variant in the `variants` option of the `addUtilities` method. 

```
addUtilities(newUtilities, {
        variants: ['focus']
});
```
