### ISSUE TITLE
Input bottom borders

### ISSUE THREAD

**Issue by randohinn** [tailwindcss/discuss#2]
copy-paste from msg to Adam on the Laravel slack: 

Hi there! I was wondering - can't seem to set just a bottom border for inputs in tailwind.. doing `border-none border-b border-grey-dark` results in border none being the most powerful one...  :confused: (edited)

**Comment by jackmcdade** [comment]
I think you just need to set a width too. The reset sets the width to 0.

**Comment by ovvessem** [comment]
Try this:

```
border-0 border-b-2 border-grey-dark
```

**Comment by reinink** [comment]
Should just have to do:

```html
<div class="border-b border-grey-dark"></div>
```

**Comment by reinink** [comment]
Or, if you don't have an input reset:

Should just have to do:

```html
<div class="border-b border-t-0 border-l-0 border-r-0 border-grey-dark"></div>
```

Pretty ugly, I agree. Generally I create components for my inputs.
