### ISSUE TITLE
Using @apply with custom addComponents

### ISSUE THREAD

**Issue by mikoelsuperbeasto** [tailwindcss/discuss#202]
Hello,

I'm kind of new with Tailwind and i would like to make my plugin to work when i call it like:
`
div {
@apply .bp;
}
`

But i'm getting this error: `@apply` cannot be used with `.bp` because `.bp` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.bp` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS,as `@apply` can only be used for classes in the same CSS tree.

Here the source:

`
module.exports = function() {
    return function ({addComponents, config, e}) {
        const screens = config('screens', []);

        const CssDebugger = {
            '.bp': {
                '&::after': {
                    content: '',
                    position: 'fixed',
                    left: '-50%',
                    top: '50%',
                    zIndex: '999',
                    fontFamily: config('fonts.mono').join(),
                    fontWeight: config('fontWeights.bold'),
                    fontSize: config('textSizes.xs'),
                    display: 'block',
                    textAlign: 'center',
                    height: '30px',
                    lineHeight: config('leading.none'),
                    width: '100%',
                    pointerEvents: 'none',
                    transform: 'rotate(-90deg)  translateY(50%)',
                    color: config('colors.red')
                }
            }
        };

        const mediaQueries = Object.entries(screens).map(([key, value]) => {
            return {
                [`@media (min-width: ${value})`]: {
                    '.bp': {
                        '&::after': {
                            content: '"@screen ' + `${key}` +' (min-width: ' + `${value}` +')"',
                        }
                    }
                }
            }
        });

        addComponents([ CssDebugger, ...mediaQueries] )
    }
}
`

Any clues for my?

**Comment by adamwathan** [comment]
Right now apply can’t be used to apply classes that contain pseudo classes
or are defined within media queries, just like the error message says. Your
`.bp` class contains the `::after` pseudo class and has multiple extra
definitions that are all inside media queries, so it doesn’t work for the
reasons stated in the error message.

**Comment by mikoelsuperbeasto** [comment]
ahh great thanks! Like the .container component class! I should have thought about it!
