### ISSUE TITLE
Container doesn't work with media query? How to customize container?

### ISSUE THREAD

**Issue by antimodern** [tailwindcss/discuss#207]
I found it's very restricting havinf `max-width` default equal to media query. First I tried `md:container` but it's does't work. Then I tried to find how do I customize container to have other `max-width` and didn't find anything. So, whta should I do in such case? Write my own styles? No info in docs regarding this.

**Comment by adamwathan** [comment]
The only point of the container class is to constrain width to the current breakpoint, it doesn't do anything else other than that. What are you actually trying to do instead?

**Comment by antimodern** [comment]
@adamwathan yes, but when `max-width` of container is equals to it's breakpoint then on certain point it's too narrow and restricting. This is what I mean

![screenshot from 2018-12-19 23-58-08](https://user-images.githubusercontent.com/45076741/50250662-28029800-03ea-11e9-865b-2fdc300d1df6.png)

```css
@media (min-width: 576px)
.container {
    max-width: 576px;
}
```
For some cases `max-width` should be bigger. Probably then I could not use Tailwind `container` at all, just custom class, but still wondering maybe there's some workaround, since there's so many options out there?

**Comment by antimodern** [comment]
After all I made `container-fluid` class, now it's seems logical.

**Comment by adamwathan** [comment]
What does your `container-fluid` class do out of curiousity?

**Comment by antimodern** [comment]
@adamwathan just restricts final `max-width` while fluent in other breakpoints

```css
.container-fluid {
  max-width: config('screens.xl');
}
```

**Comment by ahsath** [comment]
I was about to open a new issue regarding what @bdrtsky said in the first comment. I Think I'll go with the custom approach by generating custom utilities classes for this purpose

**Comment by AKopelevich** [comment]
> @adamwathan just restricts final `max-width` while fluid in other breakpoints
> 
> ```css
> .container-fluid {
>   max-width: config('screens.xl');
> }
> ```

Thank you for this solution, @bdrtsky. I just encapsulated it in a micro plugin like this:

```
plugins: [
        function ({addComponents,config}) {
            const containerFluid = {
                '.container-fluid': {maxWidth: config('theme.screens.lg')}
            }
            addComponents(containerFluid)
        }
    ],
```
