### ISSUE TITLE
How to add a plugin without loosing the .container plugin?

### ISSUE THREAD

**Issue by denjaland** [tailwindcss/discuss#208]
Hi,

I tried adding a plugin for the first time, using the plugins option in the tailwind.js file:

```
plugins: [
       function({ addUtilities }) {
           const newUtilities = {
               '.-rotate-45': {
                   transform: 'rotate(-45deg)',
               },
               '.rotate-45': {
                   transform: 'rotate(45deg)',
               },
               '.rounded-bl-none': {
                   'border-bottom-left-radius': 0
               }
           };

           addUtilities(newUtilities, {
               variants: ['responsive', 'hover', 'group-hover'],
           })
       }
   ]
```

when doing so, I noticed my `.container` class disappeared.  I noticed that it is declared in the defaultConfig file that comes with the library.

So I changed my plugins to the following:

```
plugins: [
       require('tailwindcss/plugins/container'),  // <-- ADDED THIS LINE
       function({ addUtilities }) {
           const newUtilities = {
               '.-rotate-45': {
                   transform: 'rotate(-45deg)',
               },
               '.rotate-45': {
                   transform: 'rotate(45deg)',
               },
               '.rounded-bl-none': {
                   'border-bottom-left-radius': 0
               }
           };

           addUtilities(newUtilities, {
               variants: ['responsive', 'hover', 'group-hover'],
           })
       }
   ]
```

I thought this would fix it again, as my tailwind.js is overriding the defaultconfig plugins config...  Unfortunately, it doesn't seem to fix it.  What am I missing?

**Comment by tlgreg** [comment]
The container can take options, so you still need to run it.

**Comment by denjaland** [comment]
I don't understand what you say...
Basically, I copied the `require('tailwindcss/plugins/container'), ` line from the defaultconfig in the tailwindcss... What do you mean by "I need to run it"?

**Comment by denjaland** [comment]
okay - got it...  just need to invoke the method... let me try that!

**Comment by denjaland** [comment]
Thanks!!! 
Doing `require('tailwindcss/plugins/container')(),`works!
