### ISSUE TITLE
Chaining variants

### ISSUE THREAD

**Issue by klickreflex** [tailwindcss/discuss#215]
While working on a solution for my desire to use first-child and last-child selectors with utilities ([#214]) I came across the problem of wanting to use a certain variant only at a certain breakpoint. So what I mean by _chaining variants_ is making it possible to build utilities like `.lg:hover:bg-blue`, e.g. a utility that only triggers a certain state _at a certain breakpoint_. 

While pondering about this I keep on coming back to the thought that maybe media queries should be treated differently than any other variant. I'm aware that this would be a massive breaking change, but  have you considered solving media queries the ShedCSS way? They using the `@` character to separate breakpoints and append it to the actual utility. This would allow to build more human readable classes such as`hover:bg-blue@lg`.

The concrete use-case for this: I wrote a plugin to provide a last-child variant I would like to remove the border-right of a parent's last child _only at a certain breakpoint_.

**Comment by adamwathan** [comment]
You can already do this, just enable your `last-child` variant and the `responsive` variant for the same module and classes like `.lg:last-child:border-r` will be generated automatically 👍 

A couple examples that are in the default build:

![image](https://user-images.githubusercontent.com/4323180/51181215-8fe8b900-1898-11e9-8a70-dd6c94d3196a.png)

**Comment by klickreflex** [comment]
Now I feel stupid. Should've just tried – everything already works as I need it :D `lg:last-child:bg-black`.  Awesome, thanks for pointing it out 👍 

Am I right that the order determined by the order in which variants are enabled for each module?

**Comment by adamwathan** [comment]
Yep you're right about the order, except for responsive which always comes at the end of the stylesheet in the order your screens are defined 👍🏻
