### ISSUE TITLE
can't find ./node_modules/.bin/tailwind

### ISSUE THREAD

**Issue by Eleaf** [tailwindcss/discuss#216]
Installing tailwind on OS X with npm, but can't figure out where it's installing the node module.  Nothing gets added to the current directory.

npm install tailwindcss --save-dev

npm WARN saveError ENOENT: no such file or directory, open '/Users/ethan/Web/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/ethan/Web/package.json'
npm WARN Web No description
npm WARN Web No repository field.
npm WARN Web No README data
npm WARN Web No license field.

+ tailwindcss@0.7.3
updated 1 package and audited 435 packages in 1.282s
found 0 vulnerabilities

 ethan@ET  ~/Web/craftweb.co     ls
 ethan@ET  ~/Web/craftweb.co   ./node_modules/.bin/tailwind

zsh: no such file or directory: ./node_modules/.bin/tailwind

I searched node_modules in /usr/local/lib/node_modules/npm/node_modules
and also node_module directories in ~/.nvm/ and couldn't find 'tailwind' anywhere.

Node is installed via nvm (with nvm installed via homebrew).  Node version is current stable v11.

**Comment by Eleaf** [comment]
Well, I was able to get this work by installing tailwind globally.
npm install tailwindcss --save-dev -g
~/.nvm/versions/node/v11.6.0/bin/tailwind -> ~/.nvm/versions/node/v11.6.0/lib/node_modules/tailwindcss/lib/cli.js

Now I can run 'tailwind' in the terminal and it comes up correctly.  Any issues with using tailwind this way?  It seemed like it wouldn't install the command line tool anywhere unless I specified a global install.

**Comment by adamwathan** [comment]
Hey @Eleaf! While that will technically work if you are only using the `tailwind` CLI tool to run your builds, you'll want to install it local to the project if you ever want to use another build tool like Webpack, Parcel, etc.

Start by initializing a new project with `npm init` and follow the prompts so you end up with a `package.json` file, then run `npm install tailwindcss --save-dev` and it should work as expected.

**Comment by Eleaf** [comment]
@adamwathan 
Thanks man, I was missing the package.json file and 'npm init' what what I needed to install the packages locally on a fresh project.
