### ISSUE TITLE
Add hover as default for cursor module

### ISSUE THREAD

**Issue by jan-dh** [tailwindcss/discuss#218]
It's something I find myself adjusting in a lot of projects and I can't really think of any implementations of the cursor-pointer for example, without a hover state.

**Comment by adamwathan** [comment]
The `cursor` property only ever applies on hover already, you don't need to specify `hover:cursor-pointer` for example because the hover is implied.

Here's an example in raw CSS (no Tailwind at all) that shows that the cursor property only applies on hover:

https://jsfiddle.net/fc7khtbL/
