### ISSUE TITLE
Showcase Showdown!

### ISSUE THREAD

**Issue by joshmanders** [tailwindcss/discuss#22]
![](http://images2.onionstatic.com/avclub/5527/24/16x9/960.jpg)

Would be awesome to have a showcase section added to the docs to show off sites, apps, projects, and diddle daddles that use Tailwind!

**Comment by adamwathan** [comment]
100% we are definitely gonna do this!

**Comment by joshmanders** [comment]
You're the bestest. Will you adopt me as your child? (I think I may be older than you but who cares.)

**Comment by psren** [comment]
Optional field for the show case: "How many lines of css did you write"

**Comment by mkarnicki** [comment]
Is this the best week of 2017 or what?! ❤️
_runs happy around in circles_

**Comment by joshmanders** [comment]
*frolics gingerly with @mkarnicki*

**Comment by m1guelpf** [comment]
How about making an _awesome-tailwind_ list?

**Comment by joshmanders** [comment]
@m1guelpf done. https://github.com/merchedhq/awesome-tailwindcss

**Comment by mkarnicki** [comment]
@joshmanders Would it perhaps make more sense to host awesome-tailwindcss under tailwindcss github project instead merchedhq? If I understand correctly, that's a pretty low maintenance repo (basically accepting PRs). What do you think, @adamwathan ? If that's noise to you though, we'll understand.

**Comment by joshmanders** [comment]
@mkarnicki doesn't matter where really, but if they want that's fine.

**Comment by m1guelpf** [comment]
@mkarinick We can use the vue approach (hosting it inside organization) or the unofficial approach (hosting it in our own repository and maybe linking to it, but keeping it unofficial)
