### ISSUE TITLE
Set all links to have a default of no-underline

### ISSUE THREAD

**Issue by thestepafter** [tailwindcss/discuss#23]
How can I set a global `.no-underline` for links like you have for the docs? I tried to see where you are setting it but `.no-underline` only works for me if I put it on each anchor tag. I even tried putting it on the body tag.

**Comment by psren** [comment]
@thestepafter there are multiple ways.

---

You can still write regular css!! (I'd recommend that one)
```css
a { text-decoration: none; }
```

---

With @apply
```css
a { @apply .no-underline }
```

---

Attach it to each link. From a usability-perspective I like the underline :-D
So i remove it from my main-navigation only by adding the css-class.
Or add it in a extracted component.

**Comment by thestepafter** [comment]
Ugh, makes sense. I was over engineering it too much.

**Comment by psren** [comment]
@thestepafter happens to the best of us :-D

**Comment by jhabdas** [comment]
I was looking to apply some link treatments for my color theme. Happy I found this. Seems like a pattern which should be called out in the docs a little more visibly (in the colors section, specifically) given it's something a majority of users might do.
