### ISSUE TITLE
How to make `addUtilities` work in Tailwind V1.0

### ISSUE THREAD

**Issue by agm1984** [tailwindcss/discuss#234]
At the moment, I only have one utility plugin, but it's not working as I upgrade to V1.0.

I have this:
``` javascript
    plugins: [
        ({ addUtilities }) => addUtilities({
            '.outline-pink-400': {
                outlineColor: module.exports.theme.colors['pink-400'],
            },
        }),
    ],
```

But I can't compile because of this error:

> (194:16) `@apply` cannot be used with `.outline-pink-400` because `.outline-pink-400` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.outline-pink-400` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

```
> 194 | button:focus { @apply .outline-pink-400; }
      |                ^
  195 | button:active { @apply .outline-pink-400; }
```

I find the docs very confusing towards rectifying this: https://tailwindcss.com/docs/plugins/. I need to see an example of someone adding a class of arbitrary name in Tailwind 1.0.

The above code works in Tailwind 0.7.4 (in case any future Googlers are looking).

**Comment by adamwathan** [comment]
Docs haven’t been updated yet (working on new docs at next.tailwindcss.com,
the existing docs are for version 0.7.4 like the top corner of the page
says) but as far as I can guess the problem in your example is you need to
switch colors['pink-400'] to colors.pink[400], just a guess though because
posting from my phone and can’t test.

**Comment by agm1984** [comment]
Update: The problem appears to be on `// outlineColor: module.exports.theme.colors['pink-400'],` because I changed the plugin to:

``` javascript
    plugins: [
        ({ addUtilities }) => addUtilities({
            '.outline-pink-400': {
                outline: 'none',
                // outlineColor: module.exports.theme.colors['pink-400'],
            },
        }),
    ],
```

and I was able to pass that `@apply` error onto the next one, which is amazing but I will still appreciate to learn how to call colours like that FROM the tailwind file.

Before, I could call `colors.pink` from inside tailwind.js, but now the Object composition is slightly different, so I can't do that. While I was inspecting the library code, I saw some evidence of `config('parent.child')`, but I'm not sure if that's the way I should approach this.

My naive attempt was to just call the export object as I showed above, but clearly that is generating some kind of error along the way, maybe my syntax is way off :) I'm tempted to just do something like:

``` javascript
const tailwind = { /* everything */ };
module.exports = tailwind;
```

Also I see your reply there doctor Wathan, thanks lemme take a look. I think you are 100% correct because I didn't notice the gradient values are actually keys on the `pink` object. That should fix it, thanks!!

**Comment by agm1984** [comment]
Confirmed, that fixed it.

**Comment by agm1984** [comment]
Extra for anyone later, read the upgrade path docs at least once before panicking:

![image](https://user-images.githubusercontent.com/17655219/55027297-2a185c00-4fc2-11e9-8fa5-bf58a79b03e9.png)

source: https://github.com/tailwindcss/tailwindcss/releases#update-tailwind

That usage of `theme()` pretty much answers any additional questions I may have had.

Nice work team, love the compositional tactics.
