### ISSUE TITLE
Unexpected "\" symbol in WeChat MiniProgram

### ISSUE THREAD

**Issue by mingyoung** [tailwindcss/discuss#237]
I want to use tailwindcss in my [WeChat MiniProgram](https://developers.weixin.qq.com/miniprogram/en/dev/framework/view/wxml/). But some syntax MiniProgram doesn't support it. (`\` symbol seems not be supported.)

<img width="359" alt="WX20190329-152953@2x" src="https://user-images.githubusercontent.com/6228858/55216467-c008ec80-5237-11e9-8765-cab69a393df4.png">

Is there any way to solve this?

Thanks

**Comment by tlgreg** [comment]
I'm not familiar with WeChat, but you can change the separator in the config to something else that doesn't need to be escaped. You will also need to change some utility names too, specifically the percentage width classes (the `/` in a classname needs to be escaped too).

**Comment by mingyoung** [comment]
Thanks! @tlgreg
