### ISSUE TITLE
Should I start with TailwindCSS 1.0?

### ISSUE THREAD

**Issue by SHxKM** [tailwindcss/discuss#238]
I've read v1.0 will have breaking changes, should I start with it although it's not a stable release? This project isn't going into production soon but I would like some stability at least.

**Comment by adamwathan** [comment]
I would for sure 👍🏻 the main blocker to the final release is just making
sure the documentation is fully updated.

**Comment by SHxKM** [comment]
Go it. Thanks for your hard work!
