### ISSUE TITLE
Compiling Tailwind with SASS, Gulp & package.json

### ISSUE THREAD

**Issue by tyssen** [tailwindcss/discuss#241]
I wasn't really sure where the best place to ask this question is as I'm working on customising [this set-up](https://github.com/nystudio107/craft) which relates to a specific CMS but it's the Tailwind/Gulp part I'm having trouble with.

I've used Tailwind and Gulp before but this time I'm moving all the configuration into a `package.json` as described in the Craft scaffolding project link above. So I think it's in there that I'm going wrong.

What's happening is that the output CSS is including normalize.css at the top (which is expected, see the code below), and also correctly compiling my SASS code, but it's printing out

    @tailwind preflight;
    @tailwind components;

etc. instead of outputting the CSS.

So with a SCSS file that looks like

    @charset "UTF-8";
    @tailwind preflight;
    @tailwind components;

     @import
      "components/mixins",
      …other scss files…
    ;
    @tailwind utilities;

the CSS output looks like

    /* Normalize.css code */

    @tailwind preflight;
    @tailwind components;

    /* Compiled SCSS code */

    @tailwind utilities;

My Tailwind file is exactly the same as https://github.com/nystudio107/craft/blob/master/tailwind.js and my Gulpfile is pretty much the same as https://github.com/nystudio107/craft/blob/master/gulpfile.js except that I've removed the Vue components, critical CSS, favicon and fontello functions which I'm not using.

My `package.json` file looks like 

        {
            "paths": {
                "src": {
                    "base": "./src/",
                    "css": "",
                    "img": "./src/img/",
                    "js": "./src/js/",
                    "scss": "./src/scss/"
                },
                "dist": {
                    "base": "./public_html/",
                    "css": "./public_html/assets/css/",
                    "js": "./public_html/assets/js/",
                    "fonts": "./public_html/assets/fonts/",
                    "img": "./public_html/assets/img/"
                },
                "build": {
                    "base": "./build/",
                    "css": "./build/css/",
                    "js": "./build/js/",
                    "html": "./build/html/",
                    "img": "./build/img/"
                },
                "tailwindcss": {
                    "src": "./src/scss/master.scss", // not sure about this line
                    "conf": "./tailwind.js"
                },
                "scss": [{
                    "src": "./src/scss/master.scss" // or this one
                }],
                "templates": "./public_html/site/templates/"
            },
            "vars": {
                "siteCssName": "site.combined.min.css",
                "scssName": "master.scss", // or this one
                "cssName": "master.css" // or this one
            },
            "globs": {
                "distCss": [
                    "./node_modules/normalize.css/normalize.css",
                    "./build/css/*.css"
                ]
            },
        }

Everything else is pretty much the same as https://github.com/nystudio107/craft/blob/master/package.json The difference between my setup and the Craft scaffolding one is that I'm using `src/scss/` instead of `src/css/`.

Edit: just realised that it's not completely compiling the SCSS code properly because any `@apply` or `@screen` statements are being printed as written.

**Comment by seamusmh** [comment]
I use this same setup. Did you remove dependencies & devDependencies from package.json? I believe when you fire ./nys-setup after the initial installation it goes in and adds all the necessary node modules, include tailwind.

**Comment by tyssen** [comment]
It turns out the problem was this:

     "tailwindcss": {
         "src": "./src/scss/master.scss",
      }

should've been this:

     "tailwindcss": {
         "src": "./build/css/master.css",
      }

although even with that `@tailwind components` is still being printed out and the output isn't minifed. But at least the rest of the Tailwind styles are now being included.

**Comment by seamusmh** [comment]
Progress!
