### ISSUE TITLE
Extend colors instead of overriding them in tailwind v1.0

### ISSUE THREAD

**Issue by arnedesmedt** [tailwindcss/discuss#242]
Is there a possibility to extend the colors in tailwind 1.0 instead of overrriding them. Now, I have to copy all the default values in my tailwind.config.js. Thanks in advance!

**Comment by adamwathan** [comment]
Yep you can extend things in the config file using the `extend` key under `theme`:

```js
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      colors: {
        magenta: {
          100: // ...,
          // ...
          900: // ...,
        }
      }
    }
  }
}
```

**Comment by arnedesmedt** [comment]
Thanks for the info and the awesome library!

**Comment by simondavies** [comment]
I have been tying this and I am still having to add the default values to my config file:

I am using Tailwind version 1.0.4.
 My Config is as follows:

```javascript

module.exports = {
  theme: {
    extend: {
      fontFamily: {
        title: ["Baloo"],
        sans: [
          "Rubik",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"'
        ]
      },
      colors: {
        black: "#5D5D5D",
        gray: {
          550: "#838890"
        },
        yellow: "#fdcf44",
        purple: {
          550: "#8F6EA7"
        }
      }
    }
  },
  variants: {}
};
```

I am using also `border-purple-100` and it errors on me.

```
@apply cannot be used with .border-purple-100 because .border-purple-100 either cannot be found, or its actual definition includes
```

I am also using `bg-gray-200` to test and its not showing up, unless i add ALL the gray / purple colours i need etc.

IM doing a Vue JS with NuxtJS

**Comment by tlgreg** [comment]
What you do is right in the end. The explanation is fairly simple, it's shallow merging, only a single level. With your example, you still have the `indigo` color untouched for example, it is merged in because you didn't specify anything else for that.

**Comment by simondavies** [comment]
@tlgreg Thanks for clarifying this :-)

**Comment by codex-zaydek** [comment]
I’m looking for a little advice.

I was hoping to alias the colors with a default property so I can access them a little more easily, like `bg-gray` instead of `bg-gray-500`, so I attempted the following:

```js
module.exports = {
	theme: {
		extend: {
			colors: {
				gray:   { default: "#a0aec0" },
				red:    { default: "#f56565" },
				orange: { default: "#ed8936" },
				yellow: { default: "#ecc94b" },
				green:  { default: "#48bb78" },
				teal:   { default: "#38b2ac" },
				blue:   { default: "#4299e1" },
				indigo: { default: "#667eea" },
				purple: { default: "#9f7aea" },
				pink:   { default: "#ed64a6" },
			},
		},
	},
}
```

But it looks like that ends up overriding all of the colors with the new default member, as supposed to extend the colors *with* a default member.

I also tried:

```js
	// ...
	red: {
		...defaultTheme.colors.red,
		default: "#f56565",
	},
	// ...
```

But got a reference error in the console:

```ReferenceError: defaultTheme is not defined```

Any advice? Thank you!

**Comment by codex-zaydek** [comment]
I think this most likely answers the problem: https://tailwindcss.com/docs/theme/#referencing-the-default-theme.

Sorry about that — feel free to ignore my previous comment.
