### ISSUE TITLE
Large spacing between paragraphs

### ISSUE THREAD

**Issue by peterlamar** [tailwindcss/discuss#248]
I am working on a Hugo [site](https://github.com/peterlamar/devpattern) in tailwind and my text looks awful. The spacing is too large between paragraphs. It seems either I have no spacing or I use tailwind's settings and its too much. Any advice? I hope I am missing something obvious. The text is currently styled with this line:

"class=" antialiased md:text-xl leading-tight whitespace-pre-wrap "

![largespaces](https://user-images.githubusercontent.com/5984638/56625281-978fca80-660a-11e9-8582-cfa47d159262.PNG)

**Comment by tlgreg** [comment]
If you use tailwind's base/preflight there shouldn't be any global margin between paragraphs.

**Comment by peterlamar** [comment]
I believe I am. I went over to https://github.com/tailwindcss/webpack-starter which I believe has this already, correct me if I am wrong. 

I modified the html in the webpack starter and observe the same super large spacing. 

```
<!doctype html>
<html lang="en">
  <head>
    <title>Tailwind Starter Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>
  <body>
    <div class="min-h-screen flex items-center justify-center">
      <h1 class="text-5xl text-purple font-sans">Greetings.</h1>
    </div>
    <div class=" antialiased md:text-xl leading-tight whitespace-pre-wrap ">
      <p>lorem ipsum dolor sit amet consectetur adipisicing elit. omnis id natus itaque. praesentium veritatis, iure exercitationem voluptatibus in maxime facilis iste odio sit laboriosam dolor unde, quo saepe itaque eius!</p>
      <p>lorem ipsum dolor sit amet consectetur adipisicing elit. omnis id natus itaque. praesentium veritatis, iure exercitationem voluptatibus in maxime facilis iste odio sit laboriosam dolor unde, quo saepe itaque eius!</p>
      <p>lorem ipsum dolor sit amet consectetur adipisicing elit. omnis id natus itaque. praesentium veritatis, iure exercitationem voluptatibus in maxime facilis iste odio sit laboriosam dolor unde, quo saepe itaque eius!</p>
    </div>
  </body>
</html>
```

![spacing2](https://user-images.githubusercontent.com/5984638/56654641-8ec8e400-665e-11e9-9f80-e9717934a3d2.PNG)

**Comment by adamwathan** [comment]
This is because you are using `whitespace-pre-wrap`, remove that class.

Instead you want to add margin to the individual paragraphs:

```html
    <div class=" antialiased md:text-xl leading-tight">
      <p>lorem ipsum dolor sit amet consectetur adipisicing elit. omnis id natus itaque. praesentium veritatis, iure exercitationem voluptatibus in maxime facilis iste odio sit laboriosam dolor unde, quo saepe itaque eius!</p>
      <p class="mt-4">lorem ipsum dolor sit amet consectetur adipisicing elit. omnis id natus itaque. praesentium veritatis, iure exercitationem voluptatibus in maxime facilis iste odio sit laboriosam dolor unde, quo saepe itaque eius!</p>
      <p class="mt-4">lorem ipsum dolor sit amet consectetur adipisicing elit. omnis id natus itaque. praesentium veritatis, iure exercitationem voluptatibus in maxime facilis iste odio sit laboriosam dolor unde, quo saepe itaque eius!</p>
    </div>
```

**Comment by peterlamar** [comment]
Thanks for the response! That will work in this example I agree. What is your suggestion for getting this implemented in Hugo, where the <p> tags are auto-generated?

**Comment by adamwathan** [comment]
I usually create a class like `markdown` that I apply to a wrapper element:

https://github.com/tailwindcss/discuss/issues/243

**Comment by peterlamar** [comment]
awesome, thanks!

**Comment by peterlamar** [comment]
Confirmed, I integrated this and it looks great!

As an aside, curious about your decision of putting this directly in the css vs having it built into tailwindcss. If you would like it in Tailwind, is it a contribution opportunity? (Always enjoy putting together an open source pr when I am familiar with the use case)
