### ISSUE TITLE
group-hover is not working for me in either Codesandbox or Gatsby with Styled Components.

### ISSUE THREAD

**Issue by shawnmmatthews** [tailwindcss/discuss#252]
Hoping I'm missing something simple.

I grabbed code from https://tailwindcomponents.com/component/button-dropdown
It appears to be working as expected on their site.

I updated the module for visibility in tailwind.js on both Codesandbox and Gatsby and can't seem to get the same results with the same markup. Hovering over the button does not show the element targeted by group-hover.

Here is a link using the same html as the button-dropdown  from Tailwindcomponents and it doesn't do anything on the hover state.

https://codesandbox.io/s/2p9jj3wknr

**Comment by tlgreg** [comment]
You have to enable `group-hover` variant for the plugin you want to use with (in this case `visibility`). In that codesandbox, you are using a "CDN" version which is I assume the default config, so you would need to build your own from config.

The note about this in the docs: https://tailwindcss.com/docs/state-variants#group-hover

**Comment by shawnmmatthews** [comment]
Ok that makes sense. But in my custom tailwind.js file locally. Which is serving the css via tailwind.macro I'm experiencing the same thing it has the module set with the group-hover variant and also doesn't work. Do I need to make any other changes? Or recompile a new css file or anything?

**Comment by hacknug** [comment]
Looks to me like you're using the CDN version of Tailwind instead of building it locally on your project. You're going to need to set Parcel to build it for you (since that's the bundler you're using on your sandbox).

**Comment by shawnmmatthews** [comment]
Thanks for the help @hacknug and @tlgreg. That was the problem in codesandbox for sure. I'm trying to use https://www.gatsbyjs.org/docs/tailwind-css/#option-2-css-in-js - with an otherwise default Gatsby setup. I don't think Parcel is involved locally as Gatsby is Webpack based. The macro babel plugin is included with Gatsby by default. Where should I look for the generated CSS? Does Tailwind require any updates after making changes to tailwind.js? Thanks again for helping a Tailwind noob!

**Comment by tlgreg** [comment]
Ok, I think I've got the issue, though I do not know enough about `styled-components` or `tailwind.macro` to also provide a solution. This might be an issue with `tailwind.macro` though. I see you also opened an issue there (bradlc/babel-plugin-tailwind-components#25 for ref)
The problem seems to be that the class `group` is removed, while the `group-hover` generated styles still refer to it and not the hashed class-name.

**Comment by shawnmmatthews** [comment]
Ahh that would make sense. I wasn't sure where my issue was (with tailwind or tailwind.macro). Sorry for opening this in both locations. At least now there is a reference to it should someone else come across the same thing. I'll close this and concentrate my efforts over there. I appreciate all the help @tlgreg

**Comment by shawnmmatthews** [comment]
For anyone else that comes along. Attaching the .group class directly to the DOM node via react className will not remedy the issue unfortunately.

**Comment by solarsoft0** [comment]
so how did you go about it @shawnmmatthews

**Comment by shawnmmatthews** [comment]
Personally I dropped styled-components/emotion and am just using Tailwind in classNames as I find it easier to reason about. Apparently though adding group/group-hover as a className (and using styled components/emotion) for everything else should work.

**Comment by shawnmmatthews** [comment]
That has not been my experience personally, but others seem to have it working.
