### ISSUE TITLE
Are there Tailwind classes that can produce this CSS?

### ISSUE THREAD

**Issue by JamesChevalier** [tailwindcss/discuss#256]
Are there Tailwind classes to produce this CSS?

```css
height:calc(-4rem + 100vh); width:66.66%;
```

I've created [this Pen in CodePen](https://codepen.io/jameschevalier/pen/joPvgZ) to show the context of what I'm trying to do.

**Comment by tlgreg** [comment]
Not a single class, no. Tailwind as a utility framework aims for single-property classes.

If that's not the point, then the width already exists, actually with a few names eg.: `w-2/3`
For the height, you can add it to the config like `'almost-screen': 'calc(-4rem +100vh)'`, you can pretty much have anything as a value.

**Comment by JamesChevalier** [comment]
Thanks!
I can't believe I flaked on `w-2/3` 😳 🤦‍♂ 
I came up with this configuration, just in case anyone else wanders along:

```js
module.exports = {
  theme: {
    extend: {
      height: {
        'almost': 'calc(-4rem + 100vh)',
      }
    }
  },
  variants: {},
  plugins: [],
}
```

Which lets me use `h-almost` as a class. 👍 🚀

**Comment by adamwathan** [comment]
We actually have a custom class like that in the Tailwind docs as well, here's how I have it set up:

```js
module.exports = {
  theme: {
    extend: {
      maxHeight: {
        '(screen-16)': 'calc(100vh - 4rem)',
      },
    }
  }
}
```

Looks like this in use:

```html
<div class="max-h-(screen-16)"></div>
```
