### ISSUE TITLE
Timing of the 1.0.0 stable release?

### ISSUE THREAD

**Issue by connecteev** [tailwindcss/discuss#259]
@adamwathan  thanks for tailwind.

Before upgrading to https://next.tailwindcss.com/
what is the timing of the 1.0.0 stable release?

We're afraid of doing something like this to our composer.json file
```
# Using npm
npm install tailwindcss@next --save-dev

# Using Yarn
yarn add tailwindcss@next --dev

```
What happens after 1.0.0 is released?

**Comment by MichaelDeBoey** [comment]
The latest beta is already very stable, so you could just start using that one already.

If something still changes, it will be minor things.

**Comment by adamwathan** [comment]
Will be out Monday.

**Comment by connecteev** [comment]
@MichaelDeBoey agreed.

@adamwathan awesome, and thanks! tailwind is amazing.
