### ISSUE TITLE
Multiline @apply

### ISSUE THREAD

**Issue by nauvalazhar** [tailwindcss/discuss#262]
Hi,
Congratulations on this cool framework. I'm working on a project with Tailwind and I found the `@apply` directive. My question is, to write multiline classes, then use a method like this:

```
.btn {
   @apply font-bold;
   @apply py-2;
   @apply px-4;
   @apply rounded;
}
```
Are there other ways, such as adding parentheses to organize the classes and avoid calling directives repeatedly. Maybe like this:
```
.btn {
  @apply (
     font-bold
     py-2
     px-4
     rounded
  );
}
```

Did I miss anything?

Thank you!

**Comment by hacknug** [comment]
You can already do that, only thing is you don't need the parenthesis. You can see an example in [this codesandbox](https://codesandbox.io/s/1vqxry9kj?fontsize=14&module=%2Ftailwind.css) (ignore the first line formatting _issues_ since it formats on save automatically 😅).

```css
.btn {
  @apply
     font-bold
     py-2 px-4
     rounded
  ;
}
```

**Comment by nauvalazhar** [comment]
Cool. My bad, I didn't realize that. Thank you for your reply.
