### ISSUE TITLE
You may need an appropriate loader to handle this file type error

### ISSUE THREAD

**Issue by FLasH3r** [tailwindcss/discuss#265]
Hi,
I've created a fresh webpack project but can't seem to even start using tailwindcss.

getting this error:
![image](https://user-images.githubusercontent.com/1413249/58003478-8e026100-7ae9-11e9-8aa9-d3f9bca21e0d.png)

this is my postcss.config.js
![image](https://user-images.githubusercontent.com/1413249/58003506-9a86b980-7ae9-11e9-94ca-17c3ddab1163.png)

when hovering the require of tailwindcss the tooltip says:
```
Could not find a declaration file for module 'tailwindcss'. 
'/Users/**/SideProjects/**/**/**/node_modules/tailwindcss/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/tailwindcss` if it exists or add a new declaration (.d.ts) file containing `declare module 'tailwindcss';`
```

what am I missing?

**Comment by adamwathan** [comment]
Can you post your package.json and webpack config?

**Comment by FLasH3r** [comment]
oh man, I made a typo in my webpack config
