### ISSUE TITLE
Can't get :active pseudo class to work

### ISSUE THREAD

**Issue by theomjones** [tailwindcss/discuss#267]
I'm trying to add an active class to a button but it won't work. `:hover` does work, but `:active` doesn't add any additional style.

```html
 <button
    class="bg-blue-700 shadow border-none text-yellow-100 px-2 py-1 rounded text-base cursor-pointer hover:bg-blue-800 active:bg-blue-500 outline-none"
  >
   Click!
  </button>
```

Does anyone know if there's additional configuration needed?

I've added this line to `tailwind.js` - not sure if it's needed: 
```js
variants: ["responsive", "group-hover", "hover", "focus"],
```

Thanks!

**Comment by adamwathan** [comment]
Make sure you include the “active” variant in your variants config to enable it 👍🏻

**Comment by theomjones** [comment]
Oops, completely missed the fact I didn't have that in there, thanks for your help. 
Is there any info on how much each variant weighs in terms of kb?
