### ISSUE TITLE
CSS specificity broken in v1.0.1 (Rails 5 / Webpacker)

### ISSUE THREAD

**Issue by HashNotAdam** [tailwindcss/discuss#268]
Since upgrading from v0.7.4 to v1.0.1, I've found that utilities always come before my own styles in the compiled CSS regardless of where the import statement is placed. This means that I can't override my styles using the Tailwind supplied selectors.

```
@import "tailwindcss/base.css";
@import "tailwindcss/components.css";

.button {
  @apply cursor-pointer;
  @apply font-bold;
  @apply inline-block;
  @apply mt-2;
  @apply no-underline;
  @apply px-6;
  @apply py-3;
  @apply rounded-full;
  @apply text-lg;
  @apply text-center;
  @apply tracking-tighter;
}

.main-button {
  @apply bg-green-500;
  @apply border-green-500;
  @apply button;
  @apply text-white;
}

@import "tailwindcss/utilities.css";
```

This shows as a green button
```
<input type="submit" name="commit" value="Save" class="main-button bg-gray-300" disabled="disabled" data-disable-with="Save">
```

Looking at the compiled CSS, my styles are placed after the bulk of the Tailwind styles but before the media queries for the breakpoints.

**Comment by adamwathan** [comment]
Can you post the compiled CSS in a gist? I wonder if you're running into an issue related to postcss-import not allowing imports except at the top of a file. In your actual CSS are those buttons inlined like that or are they imported from a separate file?

Nothing has changed with regards to how that sort of thing works between 0.x and 1.0 so not sure what the root problem is. If you can create a GitHub repo that reproduces the issue happy to help troubleshoot.

**Comment by andrewmcodes** [comment]
@HashNotAdam what version of rails and what version of webpacker?

**Comment by HashNotAdam** [comment]
Sorry about the delay

[Here is a gist](https://gist.github.com/HashNotAdam/4d2dd7964c01a56da81b3c37e25210a6)

Tailwind 1.0.1
Rails 5.2.2.1
Webpacker 3.5.5

**Comment by HashNotAdam** [comment]
I've also [created a repo](https://github.com/HashNotAdam/tailwind_webpacker_test) using Rails 5.2.3, Webpacker 4.0.7, and Tailwind 1.0.1

**Comment by HashNotAdam** [comment]
Okay, I think I've narrowed it down to something involving PostCSS.

If I switch from SCSS to CSS files and change the imports from:
```
@import "tailwindcss/base.css";
```
to
```
@tailwind base;
```
things start to work again and utilities come after my styles.

Clearly, this isn't actually a tailwind issue but it would be nice if could come up with a solution to post here. I've been looking through the PostCSS plugins but haven't yet worked out exactly which one is the culprit.

**Comment by HashNotAdam** [comment]
Okay, I've pushed an update that breaks up the SCSS files at the application.js level rather than having a root application.scss that imports. It seems that postcss-import is only able to group media queries that are imported into the same SCSS file.
