### ISSUE TITLE
[Question] Custom Plugin & Responsive Helpers

### ISSUE THREAD

**Issue by robmellett** [tailwindcss/discuss#271]
Hey Adam,

Thanks for putting your sweat and blood in tailwind, can't express how much I'm enjoying it right now :)

I'm trying to make a custom tailwind plugin to do the following with lists and column count attribute:

```html
<ul style="colum-count-3">
<li>Academy Brand</li>
<li>adidas</li>
<li>Armani</li>
</ul>
```

My Tailwind plugin looks like this as per `https://tailwindcss.com/docs/plugins/#adding-base-styles`

```javascript
// tailwind.config.js
const _ = require('lodash');

module.exports = {
        listColumnCount: {
            '1' : 1,
            '2' : 2,
            '3' : 3,
            '4' : 4,
            '5' : 5,
            '6' : 6,
            '7' : 7,
        }
    },
    corePlugins: {},
    plugins: [
        function({ addUtilities, config, e }) {
            const listColumnCountUtilities = _.map(config('theme.listColumnCount'), (value, key) => {
                return {
                    [`.${e(`col-count-${key}`)}`]: {
                        'column-count': `${value}`
                    }
                }
            })

            addUtilities(listColumnCountUtilities)
        }
    ],
}
```

Sample HTML
```HTML
<ul class="col-count-3 md:col-count-4">
			<li>Academy Brand</li>
			<li>adidas</li>
			<li>Armani</li>
			<li>Ben Sherman</li>
</ul>
```

The plugin works as expected, when I use a responsive helper such as `col-count-3`, however I can't seem to get the responsive helper `md:col-count-4` working as expected.  Have I done something stupid?

Thanks buddy,

**Comment by tlgreg** [comment]
Plugins don't have variants by default.
You can specify the variants in the `addUtilities` function call like
```js
addUtilities(listColumnCountUtilities, { variants: ['responsive'] })
```

**Comment by adamwathan** [comment]
Yep @tlgreg nailed it 👍 

https://tailwindcss.com/docs/plugins/#responsive-and-pseudo-class-variants

**Comment by adamwathan** [comment]
Sorry bad habit of closing things thinking they are on the tailwindcss repo and not the discuss repo :) Feel free to close if you think your question is resolved, or don't because it doesn't matter anyways.

**Comment by robmellett** [comment]
Thank you very much @tlgreg & @adamwathan ,
