### ISSUE TITLE
Error using @apply with SASS Ampersand Class

### ISSUE THREAD

**Issue by skazzaks** [tailwindcss/discuss#272]
Hello! I am having an issue that I think might be tailwind related. I am importing code from a working env using webpack into a rails env using webpacker and can't get my css to build correctly. 

My entry file looks something like this:

```
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";

@import "./base/_fonts.scss";
@import "./base/_typography.scss";
@import "./base/_transition.scss";
@import "./base/_grid.scss";
@import "./base/_space.scss";
@import "./base/_link.scss";
```

_transition.scss contains:

```
// Timing
.timing {
  &-1 {
    transition-timing-function: ease;
  }

  &-2 {
    transition-timing-function: ease-in-out;
  }

  &-3 {
    transition-timing-function: var(--bezier-1);
  }
}
```
which should generate "timing-1"

But in _link.scss I have:
```
// Links
.link {
  @apply no-underline
        font-medium
        inline-block
        timing-1 duration-1 property-all;
```

and I get the error:
```
ERROR in ./app/javascript/stylesheets/application.css (./node_modules/css-loader/dist/cjs.js??ref--3-1!./node_modules/postcss-loader/src??ref--3-2!./app/javascript/stylesheets/application.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(3:3) `@apply` cannot be used with `.timing-1` because `.timing-1` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.timing-1` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
```

As mentioned, this works fine in another environment that was written by a contractor but I am not sure why the class can't be found in my rails/webpacker env. Maybe it has something to do with postcss but I am a bit out of my element. Here is my postcss.config.js just in case that is helpful:
```

const tailwindcss = require('tailwindcss')

module.exports = {
  syntax: require('postcss-scss'),
  
  plugins: [
    require('postcss-import'),
    require('postcss-strip-inline-comments'),
    require('tailwindcss')('./app/javascript/stylesheets/tailwind.js'),
    require('postcss-flexbugs-fixes'),
    require('postcss-nested'),
    require('postcss-preset-env')({
      autoprefixer: {
        flexbox: 'no-2009'
      },
      stage: 3
    }),
    require('autoprefixer'),
    require('precss'),
  ]
}

```

Thanks for any help you can provide.

**Comment by adamwathan** [comment]
Any chance you can provide a simple reproduction in a GitHub repo? Definitely feels like a setup issue but a lot of moving parts to work out.

**Comment by skazzaks** [comment]
Thanks for your answer - I don't think I can get to that until tomorrow but in the meantime is there any other file you'd like to see that would be helpful?

**Comment by adamwathan** [comment]
Hard to say as I've never used Rails or Webpacker but my first thought would be wanting to confirm that your Sass is actually being compiled before being processed by PostCSS. `postcss-scss` doesn't actually compile your Sass, so you need another step before that and I'm not sure where that would be defined. You shouldn't actually need `postcss-scss` for your use case.

**Comment by skazzaks** [comment]
@adamwathan I've pushed a repo that reproduces the issue here: https://github.com/skazzaks/webpacker-tailwind-test

I think you are probably right that it has to do with sass being compiled, but I don't really get how that works with PostCSS and I'm not sure that is the problem. If you have time I'd appreciate if you took a look. Thanks!

**Comment by skazzaks** [comment]
And if I take out the `postcss-scss` I get:

```
ERROR in ./app/javascript/css/application.css (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./app/javascript/css/application.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(108:9) Unknown word

  106 |       @apply text-5xl;
  107 |       &-2 {
> 108 |         // @apply text-xl font-serif leading-tight;
      |         ^
  109 |         font-size: 2rem;
  110 |       }

```

**Comment by skazzaks** [comment]
Just some more info - when I log the default webpack config  that webpacker users by adding `
console.log(environment.loaders.get('sass'))` in `config/webpack/environment.js` I get:

```
{
  test: /\.(scss|sass)$/i,
  use: [
    { loader: 'style-loader', options: [Object] },
    { loader: 'css-loader', options: [Object] },
    { loader: 'postcss-loader', options: [Object] },
    { loader: 'sass-loader', options: [Object] }
  ],
  sideEffects: true,
  exclude: /\.module\.[a-z]+$/
}
```

So it looks like it does compile the sass from the way I understand it.

**Comment by skazzaks** [comment]
Think I figured it out! My application file was named application.css and not application.scss and I think that was causing the problems. Will report back.

**Comment by skazzaks** [comment]
That did it! Thanks so much for your help. Lots of pain but finally got there. The problem was in fact that the application.css file needed to be application.scss. Wasn't obvious as the problem I go down the line didn't indicate that this was wrong.

Gonna close this out.

**Comment by adamwathan** [comment]
Awesome glad to hear you resolved it!
