### ISSUE TITLE
Improve Installation Documentation (add step for creating the config file, and for Laravel Mix)

### ISSUE THREAD

**Issue by connecteev** [tailwindcss/discuss#276]
@adamwathan Thanks for bringing tailwind to the world....but the [documentation](https://tailwindcss.com/docs/installation/ ) for installing tailwind 1.x is incomplete. Suggestions below because I just spent more time than I would've liked on this:

### Creating the config file
There is no mention of how the tailwind config file gets created, it's currently buried under [Configuration here](https://tailwindcss.com/docs/configuration/).
 
```
npx tailwind init 
or
npx tailwind init --full
(creates tailwind.config.js)
```

### Laravel Mix Config for Tailwind
Specifically for folks using tailwind with Laravel Mix, there are 2 possible ways to configure tailwind with Laravel (these configs below are geared toward sass, but should apply otherwise also if using less etc)

#### Option 1: Using laravel-mix-tailwind
Step 1. Run: npm install laravel-mix-tailwind

Step 2. Update webpack.mix.js with:
```
const mix = require('laravel-mix');

require('laravel-mix-tailwind');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
	.tailwind('./tailwind.config.js');
```

#### Option 2: Using Laravel Mix with postCss
(this is [in the docs already](https://tailwindcss.com/docs/installation/#laravel-mix))

Update webpack.mix.js with:
```
const mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */
const tailwindcss = require('tailwindcss')

mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
  .options({
    processCssUrls: false,
    postCss: [ tailwindcss('./tailwind.config.js') ],
  });
```

Would be cool to add these to the documentation so that it helps others that are stuck and is all in one place. If it's 2 wordy for the [main installation page](https://tailwindcss.com/docs/installation/), it could be added as a link to a leaf page. My 2c.

**Comment by adamwathan** [comment]
I'll think about adding instructions for creating the config file to the installation, but the config file is totally optional and not actually required for installing Tailwind, you only need a config file if you want to customize Tailwind which is why that information is currently in the "Customization" section of the docs.

Don't think we need to document two ways of installing Tailwind with Laravel Mix, I'd rather just use what we have now which doesn't depend on any extra dependencies and is still extremely simple, especially because if you want to use other PostCSS plugins using that plugin is not a great idea since you can no longer control the plugin order.

**Comment by connecteev** [comment]
Thanks for the clarification @adamwathan. I didnt know that the tailwind config file was optional until after posting this..
Re: Tailwind and Laravel Mix, that's good to know as well. What are some of the PostCSS plugins you currently use for your Laravel + Tailwind app?

**Comment by adamwathan** [comment]
I list all of my go-to PostCSS plugins in the docs here 👍 

https://tailwindcss.com/docs/using-with-preprocessors#using-postcss-as-your-preprocessor

**Comment by connecteev** [comment]
Thank you @adamwathan!
