### ISSUE TITLE
Using a custom font

### ISSUE THREAD

**Issue by nojaf** [tailwindcss/discuss#277]
Hello, I'm giving tailwind a spin and I want to use a custom font family.
Unfortunately, it is not really working out.

I have a tailwind.config.js

```
module.exports = {
    theme: {
        fontFamily: {
            body: ['Lato', 'sans-serif'],
            display: ['Lato', 'sans-serif']
        },
        extend: {}
    },
    variants: {},
    plugins: []
};
```

I'm not entirely sure if this `fontFamily` should go under theme or extend.

It is also hard to tell if my config file being picked up by webpack:
My webpack looks like:

```
// Note this only includes basic configuration for development mode.
// For a more comprehensive configuration check:
// https://github.com/fable-compiler/webpack-config-template

const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const PurgecssPlugin = require("purgecss-webpack-plugin");
const glob = require("glob");
const webpack = require("webpack");

const isProduction = !process.argv.find(
  v => v.indexOf("webpack-dev-server") !== -1
);

console.log(`Building for ${isProduction ? "production" : "development"}`);

const babel = {};

const plugins = isProduction
  ? [
      new HtmlWebpackPlugin({
        filename: "index.html",
        template: "./public/index.html"
      }),
      new MiniCssExtractPlugin({
        filename: "styles.css",
        chunkFilename: "styles.css"
      }),
      new PurgecssPlugin({
        paths: () =>
          glob.sync(`${path.join(__dirname, "src")}/**/*`, { nodir: true })
      })
    ]
  : [
      new HtmlWebpackPlugin({
        filename: "index.html",
        template: "./public/index.html"
      }),
      new webpack.HotModuleReplacementPlugin()
    ];

module.exports = {
  mode: "development",
  entry: "./src/App.fsx",
  output: {
    path: path.join(__dirname, "./docs"),
    filename: "[name].bundle.js",
    chunkFilename: "[name].bundle.js",
    publicPath: "/"
  },
  devServer: {
    contentBase: "./public",
    port: 8080,
    hot: true,
    historyApiFallback: true
  },
  module: {
    rules: [
      {
        test: /\.fs(x|proj)?$/,
        use: {
          loader: "fable-loader",
          options: {
            babel
          }
        }
      },
      {
        test: /\.pcss$/,
        use: [
          isProduction ? MiniCssExtractPlugin.loader : "style-loader",
          {
            loader: "css-loader",
            options: {
              importLoaders: 1
            }
          },
          {
            loader: "postcss-loader",
            options: {
              plugins: [require("tailwindcss"), require("autoprefixer")]
            }
          }
        ]
      }
    ]
  },
  optimization: {
    splitChunks: {
      chunks: "all"
    }
  },
  plugins
};
```

And my css like:
```
@import url('https://fonts.googleapis.com/css?family=Lato&display=swap');

/* purgecss start ignore */
@tailwind base;
/* purgecss end ignore */

@tailwind components;

@tailwind utilities;

h1 {
    @apply text-2xl pb-2;
}

.navigation {
    @apply flex bg-green-400 p-4 text-white;
}
```

I would expect that everything now uses `Lato` as font-family. What am I missing here?

**Comment by adamwathan** [comment]
Hey @nojaf, have you made sure to add the `font-body` and `font-display` classes to your HTML?

If you want `font-body` to be the default font for your whole site, I would add that class to the `html` or `body` tag:

```html
<html>
<head>
<!-- ... -->
</head>
<body class="font-body">
  <!-- ... -->
</body>
</html>
```

**Comment by nojaf** [comment]
Hi @adamwathan, thanks it is starting to make some more sense.

```
module.exports = {
    theme: {
        fontFamily: {
            body: ['Lato', 'sans-serif'],
            display: ['Lato', 'sans-serif']
        },
...
```
Leads to `font-body` being added to the css file.

`@tailwind base;` probably resets all the font to the current behaviour.
So what I think I actually want to do is override the font-family of `html` inside the css file.

Like
```css
html {
    font-family: 'Lato', sans-serif;
}
```

**Comment by adamwathan** [comment]
You could do that, or this:

```css
html {
  @apply font-body
}
```

Personally I prefer just adding the class to the `body` element.

We have documentation for all of this btw here:

https://tailwindcss.com/docs/adding-base-styles

**Comment by nojaf** [comment]
Thanks, this helped a lot!

**Comment by dakshshah96** [comment]
@adamwathan Is this still required to be done? I just began a new Gridsome project, added Tailwind CSS using the `gridsome-plugin-tailwindcss` package and configured my `tailwind.config.js` file:

```
module.exports = {
  theme: {
    fontFamily: {
      display: ['Inter', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', '"Helvetica Neue"', 'Arial', '"Noto Sans"', 'sans-serif'],
      body: ['Inter', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', '"Helvetica Neue"', 'Arial', '"Noto Sans"', 'sans-serif']
    },
    extend: {}
  },
  variants: {},
  plugins: []
}
```

I can't get the fonts to change to the ones I've mentioned in the config file 😞

**Comment by adamwathan** [comment]
Did you make sure to use the classes `font-display` and `font-body` in your HTML? You can name those keys whatever you want, by default we just have `sans`, `serif`, and `mono`.

**Comment by dakshshah96** [comment]
@adamwathan That did it, thanks so much for the quick response 💯

**Comment by kevyworks** [comment]
Maybe, Is it possible for a CDN css for example to honor something like:

```css
:root {
  --tailwind-font-family: Inter, Arial, sans-serif;
}
```

**Comment by adamwathan** [comment]
You can always write this which is even shorter:

```css
html {
  font-family: Inter, Arial, sans-serif;
}
```

**Comment by dhakan** [comment]
Hi! I've read the docs for base styles, custom fonts as well as purgecss and this thread, and I have been able to make usage of `Roboto` font via google fonts successfully. The question I have is related to purgecss:

```
/* purgecss start ignore */
@tailwind base;
/* purgecss end ignore */
```

The placement of these "ignores" seem to make or break this functionality(and not only the custom font but also the normalize like body margin). Is this something anyone could shed a light on? I assume this is something I've missed somewhere since @nojaf is using them in the code above.

I'm using tailwind with react/nextjs if that is of any help.

Thanks!

**Comment by adamwathan** [comment]
@dhakan Hey! That is probably because you have some base HTML layout file that is not being inspected by Purgecss. This is very easy to do by mistake with vue-cli, Next.js/Nuxt.js, create-react-app, etc. because there is some `index.html` file hidden in a completely different folder than the rest of your templates.

What's happening is Purgecss is stripping your `html` styles, `body` styles, etc. because it's not seeing any files that actually use those elements.

I think the best solution personally is the one you provided in your comment 👍 I would even go so far as to say it might be an even better idea to _only_ apply Purgecss to your utilities, since that's where it is most effective anyways:

```
/* purgecss start ignore */
@tailwind base;
@tailwind components;
/* purgecss end ignore */

@tailwind utilities;
```

**Comment by dhakan** [comment]
@adamwathan Thanks a bunch. This makes lots of sense. Maybe this is something to add to the purgecss setup page(https://tailwindcss.com/docs/controlling-file-size/) or the base styles page(https://tailwindcss.com/docs/adding-base-styles/) in the docs?
