### ISSUE TITLE
Tailwind Shopify Build Error

### ISSUE THREAD

**Issue by robmellett** [tailwindcss/discuss#290]
Hey Adam,

I'm hoping you can help me.

I've got this bizarrare issue with Tailwind and Shopify Slate, everything works locally when I run `yarn start`, however when I build with `yarn build` I don't think tailwind is being compilied properly and I lose all styles in the browser.  I'm not very familar with how PostCSS works. Any guidance would be greatly appreciated.

I have a sample project here.
`https://github.com/robmellett/shopify-tailwind-vue`

The files which may be of interest are:
`https://github.com/robmellett/shopify-tailwind-vue/blob/master/slate.config.js`
`https://github.com/robmellett/shopify-tailwind-vue/blob/master/.postcssrc.js`
`https://github.com/robmellett/shopify-tailwind-vue/blob/master/src/styles/theme.scss`

An example of the compiled CSS.

![image](https://user-images.githubusercontent.com/26024074/60309471-4943d280-9991-11e9-9710-2655add6eda4.png)

Thank you in advanced, more than happy to buy you a couple of beers for this one :)

**Comment by hacknug** [comment]
Tried debugging but I need some kind of credentials to be able to `yarn start`:
```shell
Some values in environment 'external' are invalid:
- Error: SLATE_STORE must not be empty
- Error: SLATE_PASSWORD must not be empty
- Error: SLATE_THEME_ID must not be empty
```

**Comment by robmellett** [comment]
Thanks for helping out :)

Yes, if you copy the `.env-sample` to `.env`, populate them with the Shopify credentials.

**Comment by taylorbryant** [comment]
One thing I notice is that you're missing `postcss-import` in `https://github.com/robmellett/shopify-tailwind-vue/blob/master/slate.config.js`.

Try adding `require("postcss-import")`.

**Comment by robmellett** [comment]
> One thing I notice is that you're missing `postcss-import` in `https://github.com/robmellett/shopify-tailwind-vue/blob/master/slate.config.js`.
> 
> Try adding `require("postcss-import")`.

Great suggestion, I've tried putting it at the top of the file and above the postcssLoader section near the `require(tailwindcss;) .  Unforunately it hasn't seem to have worked :(

**Comment by robmellett** [comment]
All good! As expected it was an issue with PostCss and Shopify Slate.

**Comment by clin407** [comment]
@robmellett did you ever figure out how to get shopify slate and tailwind working correctly?

**Comment by dungle-scrubs** [comment]
@robmellett Also wondering how you were able to resolve this (I'm experiencing something similar)

**Comment by robmellett** [comment]
> @robmellett Also wondering how you were able to resolve this (I'm experiencing something similar)

Yes.  See this repo.

https://github.com/robmellett/shopify-tailwind-vue

**Comment by dungle-scrubs** [comment]
@robmellett Thanks!
