### ISSUE TITLE
Use tailwindcss with webpack 

### ISSUE THREAD

**Issue by brahimbim** [tailwindcss/discuss#30]
## Use tailwindcss with webpack
I follow the documentation **without** success any help ?

**Comment by aaronmoodie** [comment]
@brahimbim What issues are you having? I just had to set up a project from scratch to get it working correctly.

**Comment by adamwathan** [comment]
Hey @brahimbim! I cooked up an extremely simple example starter project:

https://github.com/adamwathan/tailwind-webpack-starter

Give that a look and see if it helps.

**Comment by brahimbim** [comment]
thank you @adamwathan now it works well
