### ISSUE TITLE
property override problem

### ISSUE THREAD

**Issue by eness** [tailwindcss/discuss#302]
Hello there,

I am having a small issue on extracting custom components with tailwind.

Here, I created a .btn component as we have on other frameworks such as bootstrap, semantic ui etc.

```
.btn {
    @apply inline-block;
    @apply select-none;
    @apply py-2;
    @apply px-6;
    @apply uppercase;
    @apply rounded-full;
    @apply bg-red-400;
    @apply outline-none;
    @apply whitespace-no-wrap;
}

```

Now I can use is anywhere like 

`<a href="#" class="btn">My Button</a>`

But if I want it to appear/disappear at somebreakpoint, display property provided by breakpoint prefixed classes (or any other tailwind based class) conflicts with the base display property of my custom .btn component so tailwind's base class is unable to override it.

Here are some examples that is expected to work but fails

`<a href="#" class="btn hidden sm:block">My Button</a>`

`<a href="#" class="btn p-4">My Button</a>`

`<a href="#" class="btn lowercase">My Button</a>`

Maybe defining **!important** suffix for all values provided by tailwind would work but makes no sense at all.

**Comment by tlgreg** [comment]
Make sure `@tailwind utilities` comes after your `.btn` class. If so the above example should work.
Eg.:
```postcss
@tailwind base;
@tailwind components;
.btn {}
@tailwind utilities;
```

If your components do use higher specificity selectors though, you'll have to turn on `important` on the utilities to be able to override.

https://tailwindcss.com/docs/configuration#important

**Comment by eness** [comment]
just solved by restructuring the class definition order as shown above.
