### ISSUE TITLE
Documentation issue with @apply

### ISSUE THREAD

**Issue by Hasgaroth** [tailwindcss/discuss#308]
Firstly, I'd like to say what an awesome product Tailwind CSS is! I've only been using it for a few days since LaraconUS 2019, and I'm rolling changes out through my site now.

I have a problem with the documented example of using the `@apply` operator on page https://tailwindcss.com/docs/extracting-components

The doc states 
```
.btn-blue {
  @apply bg-blue-500 text-white font-bold py-2 px-4 rounded;
}
.btn-blue:hover {
  @apply bg-blue-700;
}
```

but if I just copy and paste that into the correct place in my scss file and run a build, I get the following error
```
ERROR in ./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/lib??postcss!./node_modules/sass-loader/lib/loader.js??ref--6-4!./resources/assets/sass/app-rtl.scss
Module build failed: Syntax Error

(10161:3) `@apply` cannot be used with .text-white because .text-white is included in multiple rulesets.
```

I _might_ be doing something wrong, but I've followed the setup docs carefully.

Thanks in advance for any advice on this one,
Dave

**Comment by adamwathan** [comment]
Can you share your CSS file? It sounds like maybe you’ve added a custom CSS rule somewhere that includes the text-white class so Tailwind no longer knows what it should do when trying to apply text-white.

**Comment by Hasgaroth** [comment]
Yeah, looks like it's something earlier in the definitions.

I had included the Laravel Spark SASS definitions before the Tailwind ones, and stripping those out does the trick. Unfortunately, including the Spark definitions anywhere in the include file fails the build, so I will have to skip creating my own utility classes with `@apply` and try creating a component plugin.

Sorry to have troubled you with this!

**Comment by nick-f** [comment]
@Hasgaroth I came across the same issue, and managed to solve it with some creative concatenation. It's not the cleanest solution, but it does give you the best of both worlds in as much as you can still use the base Spark styles, Tailwind, and use `@apply` for your own components.

```
// header.scss
@import "./../../node_modules/tailwindcss/base";
@import "./../../node_modules/tailwindcss/components";
@import "./../../vendor/laravel/spark-aurelius/resources/assets/sass/spark";
```

```
// main.scss
h1 {
  @apply font-light tracking-wide text-2xl;
}
[rest of the styles]
```

```
// webpack.mix.js
mix.sass('resources/sass/app.scss', 'public/css/header.css')
    .options({
        processCssUrls: false,
        postCss: [ tailwindcss('./tailwind.config.js') ],
    })
    .sass('resources/sass/main.scss', 'public/css')
    .options({
        processCssUrls: false,
        postCss: [ tailwindcss('./tailwind.config.js') ],
    })
    .combine(['public/css/header.css', 'public/css/main.css'], 'public/css/app.css')
```

It could probably be simplified to have the contents of `header.scss` just added as part of `webpack.mix.js`, but up to you if you want to go about it that way.
