### ISSUE TITLE
How to create sidebar with fixed width?

### ISSUE THREAD

**Issue by webbie** [tailwindcss/discuss#31]
I'm trying to make 2-column layout, where main column always takes available space, and sidebar is fixed sized: 300px on `xl`, `lg` and `md` screens. On `sm` screens should be 100%, in a row below main column.

Probably need to use additional css classes, but still not sure how to do that in tailwindcss way :) Can you give me some hints?

**Comment by mstnorris** [comment]
@webbie This is sort of what I requested [here](https://github.com/tailwindcss/discuss/issues/26). Attaching purely for reference.

**Comment by adamwathan** [comment]
Here's a quick example:

https://jsfiddle.net/jqpkbe4u/

The real key here is just getting good at Flexbox and learning how Flexbox features are exposed in Tailwind 👍

**Comment by webbie** [comment]
You're right, I need to dive into flexbox to better understand tailwind.
Thanks for example!
