### ISSUE TITLE
Background color overflows rounded corners

### ISSUE THREAD

**Issue by randyrankin** [tailwindcss/discuss#311]
Can anyone advise regarding how to prevent a background color from overflowing rounded corners? 

```
<div class="bg-gray-100 border border-gray-500 rounded-lg">
    <div class="font-semibold bg-white text-gray-700 py-2 px-4">
        Header
    </div>
    <div class="w-full py-2 px-4">
        Content
    </div>
</div>
```

![Screen Shot 2019-07-31 at 10 21 22](https://user-images.githubusercontent.com/13204196/62224893-02287300-b37d-11e9-8d0f-cf2aa3f49292.png)

**Comment by adamwathan** [comment]
Add `overflow-hidden` to the parent element.

**Comment by randyrankin** [comment]
Problem solved. Thanks Adam!
