### ISSUE TITLE
Correct way to style when using a WYSIWYG / Markdown?

### ISSUE THREAD

**Issue by mikebarlow** [tailwindcss/discuss#319]
I may already have my answer but if you've built a site with Tailwind but it's using a WYSiWYG in an admin area or a markdown to html convertor like within Jekyll sites on Github pages, what is the best way to be styling the elements within the content once the html has been created?

Obviously for the most part in this situation we have little control over the html that is generated and therefore can't assign the classes for styling so is the best way to simply modify the templates and wrap the content in a div with a class and then target all the applicable elements within the sass file? Something like this?

    .wysiwyg {
        p {
            // styles here
        }

        h1 {
            // styles here
        }

        h2 {
            // styles here
        }

        h3 {
            // styles here
        }

        h4 {
            // styles here
        }

        ul {
            // styles here
        }

        a {
            // styles here
        }
    }

Or is there another, more elegant method that I've missed?

**Comment by adamwathan** [comment]
Yep that's how I do it, here's the styles from my personal website for example:

```css
.markdown {
  @apply text-lg text-grey-darkest leading-normal;
  & > * + *,  & li + li, & li > p + p {
    @apply mt-6;
  }
  & strong {
    @apply text-black font-bold;
  }
  & a {
    @apply text-black font-semibold;
  }
  & strong a {
    @apply font-bold;
  }
  & h2 {
    @apply leading-tight text-xl font-bold text-black mb-2 mt-10;
  }
  & h3 {
    @apply leading-tight text-lg font-bold text-black mt-8 -mb-2;
  }
  & code {
    @apply font-mono text-sm inline bg-grey-lighter px-1;
  }
  & pre code {
    @apply block bg-black p-4 rounded;
  }
  & blockquote {
    @apply border-l-4 border-grey-light pl-4 italic;
  }
  & ul, & ol {
    @apply pl-5;
    @screen sm {
      @apply pl-10;
    }
  }
}
```

**Comment by mikebarlow** [comment]
Awesome, I was on the right line then! Thank you!
