### ISSUE TITLE
Weird behaviour with dropdown menus

### ISSUE THREAD

**Issue by kubacode** [tailwindcss/discuss#32]
I've been working on implementing some dropdown menus with Tailwind and I'm seeing some weird behaviour with other dropdown menu controls.

I'm sure I haven't done something correctly so would appreciate any advice anyone can provide.

When the menu is collapsed, everything looks as expected:
<img width="396" alt="screen shot 2017-11-06 at 9 49 35 pm" src="https://user-images.githubusercontent.com/4929328/32440125-8624361c-c33d-11e7-9649-78fde8df6148.png">

When the menu is expanded, controls for other dropdown menus float above the menu, even though no z-indexs have been set:
<img width="393" alt="screen shot 2017-11-06 at 9 49 51 pm" src="https://user-images.githubusercontent.com/4929328/32440126-865b299c-c33d-11e7-9f4a-bbeb3d278423.png">

Any help would be much appreciated!

**Comment by MichaelDeBoey** [comment]
Can you provide a sandboxed example?
That would be easier to help 🙂

**Comment by adamwathan** [comment]
Echoing @MichaelDeBoey's comment; if you can provide the code there's a lot more we can do to help.

Quick glance makes it look like the red boxes either have a z-index set or have `position: absolute` set which creates a stacking context and elevates them around the surrounding elements.

Since those red boxes appear *after* the dropdown in the DOM, they will have a higher effective z-index if the z-index is not actually set on either the drop down or the red boxes.

I suspect the fix for you in this case is just to assign a z-index of any value to dropdown area. I'd probably pick 20 or 30 if using the Tailwind defaults, so you still have some room above it for things like modals as well as below for anything in the main content area that needs a z-index but should be positioned under the dropdown.

**Comment by kubacode** [comment]
I've done up a [Codepen](https://codepen.io/kubacode/pen/vWyJNE) with minimal viable css, and applying the z-index to the dropdown content works as you have suggested, but applying the z-index to my site doesn't entirely fix the problem - sad face!

Applying the z-index has fixed the dropdown the red controls, but not the dropdown in the nav bar:
<img width="254" alt="screen shot 2017-11-08 at 9 58 54 pm" src="https://user-images.githubusercontent.com/4929328/32548086-2901efee-c4d0-11e7-9a0a-6cc3cef4758b.png">    <img width="291" alt="screen shot 2017-11-08 at 9 59 13 pm" src="https://user-images.githubusercontent.com/4929328/32548087-2935b4dc-c4d0-11e7-9ccc-e61fd0c513c3.png">

The markup & less file with customisations are available in this [Gist](https://gist.github.com/kubacode/6a4593130aa10cc3ad49e0cd1bc8e81a), if you have any more suggestions as to what I could be doing wrong, it would be appreciated.

Btw, totally loving Tailwind - I've never been able to design a site that looks this good (and nothing like a Bootstrap site) before!

**Comment by kubacode** [comment]
Hey @MichaelDeBoey, @adamwathan any chance you'd be able to help take a look into what might be going on here? Thanks in advance!

**Comment by MichaelDeBoey** [comment]
@kubacode Can you provide a small project (GitHub link) with only this page please? I'll take a look for you then 😉

**Comment by kubacode** [comment]
@MichaelDeBoey That would be great - I've setup a quick repo [here](https://github.com/kubacode/tailwind-example) for you. Thanks again for helping me out 😄

**Comment by kubacode** [comment]
@MichaelDeBoey were you able to take a look into this?

**Comment by MichaelDeBoey** [comment]
@kubacode Haven't had the time yet unfortunately 😕

Will try to take a look at it tonight 🙂

**Comment by MichaelDeBoey** [comment]
@kubacode Took a quick look and the problem I found was that `header` and the main container have the same `z-index`.
If you add an `z-index` (ie `z-10`) to the `header`, your problem will be fixed 🙂

**Comment by kubacode** [comment]
@MichaelDeBoey Thats fixed it - thanks for taking a look!

**Comment by AlanTheGreat2018** [comment]
@kubacode would you mind sharing your code with me? I'm trying to implement dropdown in tailwind too
