### ISSUE TITLE
Is there a way to get dynamic colors (by their names) in Inline embedded style?

### ISSUE THREAD

**Issue by daveupress** [tailwindcss/discuss#322]
Is there a way to get dynamic colors (by their names) in Inline embedded style? For example, in React within a style tag.
style={{backgroundColor: '#FF4E4F', boxShadow: 'rgba(255, 78, 79, 0.4) 0px 0px 5px 0'}}
Is there a way to get the color # FF4E4F by its name?

**Comment by hacknug** [comment]
Maybe this will help if you're working with React https://github.com/bradlc/babel-plugin-tailwind-components

**Comment by daveupress** [comment]
Thanks
