### ISSUE TITLE
CSS grid utility classes proposel

### ISSUE THREAD

**Issue by marco-van-zomeren** [tailwindcss/discuss#324]
I miss utility classes for the CSS grid standard.

Can we adopt something like:

`$sizes: xxs, xs, md, lg, xl;

@each $size in $sizes {
  .#{$size} {
    @include breakpoint(#{$size}) {
    $span: 0;
    @while $span < 12 {
        $span: $span + 1;
        &\:span-#{$span} {
            grid-column: span #{$span};
        }
    }
  }
}
}`

**Comment by hacknug** [comment]
Take a look at https://github.com/tailwindcss/tailwindcss/issues/32 and https://www.npmjs.com/package/tailwindcss-grid

**Comment by marco-van-zomeren** [comment]
Thank you, than I see this issue as a duplicate and will close it. :)
