### ISSUE TITLE
Sonarcloud css checking found a bug?

### ISSUE THREAD

**Issue by ColonelBlimp** [tailwindcss/discuss#327]
Sonarcloud has raised an issue with my tailwind css file, but I'm not sure if it is an issue:

**Unexpected duplicate text-decoration**

The offending class is below, with the offending line in **bold** and _italics_:

abbr[title] {
  border-bottom: none; 
  text-decoration: underline;
  -webkit-text-decoration: underline dotted;
  _**text-decoration: underline dotted;**_
}

My `tailwind.config.js` looks like this:

module.exports = {
  theme: {
    extend: {
      container: {
        center: true,
      },
      width: {
        '72':'18rem',
        '80':'20rem',
        '88':'22rem',
        '96':'24rem',
        '104':'26rem'
      },
      minWidth: {
      	'32':'8rem',
      	'56':'14rem'
      },
    }
  }
}

Should I report this as a bug?  Or have I incorrectly configured tailwind?

Many thanks.

**Comment by hacknug** [comment]
That line comes from normalize and shouldn't be considered a bug: https://github.com/necolas/normalize.css/blob/fc091cce1534909334c1911709a39c22d406977b/normalize.css#L80-L89

**Comment by ColonelBlimp** [comment]
> That line comes from normalize and shouldn't be considered a bug: https://github.com/necolas/normalize.css/blob/fc091cce1534909334c1911709a39c22d406977b/normalize.css#L80-L89

Many thanks.
