### ISSUE TITLE
Auto expanding div height with text overflow on smaller screens

### ISSUE THREAD

**Issue by pdevito3** [tailwindcss/discuss#329]
Hey guys, I'm working on a website with some longer text strings that have some significant overflow. The issue I'm running into comes in when accounting for a responsive design. Specifically, when you get to smaller screens and the text begins to overflow onto lower divs. Normally, I'd use tailwind's [overflow utility](https://tailwindcss.com/docs/overflow/#app) but I'm not looking to hide the text or scroll given the content.

I've been getting around this by changing the top margin for now, but it feels messy and more involved than it should be. Any recommendations for how to get around this? See attached for an example.

[htmlExample.txt](https://github.com/tailwindcss/discuss/files/3593444/htmlExample.txt)

**Comment by hacknug** [comment]
Do you really need to give the element an explicit height?

**Comment by pdevito3** [comment]
Can't believe I glossed over that! The wonder of a second et of eyes. Thanks

**Comment by hacknug** [comment]
No problem, that's why they invented the Internet, no? haha
