### ISSUE TITLE
@responsive and @screen md not working in imported scss files

### ISSUE THREAD

**Issue by paulhuisman** [tailwindcss/discuss#331]
Hi there!

When i use `@responsive` or `@screen md` in my main.scss it works fine.

However, when i try to use this in my imported scss files, it does not work.

`@import './components/_header.scss';`

**components/_header.scss**

```
@include md {
    .header {
        display: none; 
    }
}
```

Above is an example of course, but  this does not hide `.header` on MD viewport.

**Comment by adamwathan** [comment]
You should use `@screen` not `@include`:

```diff
- @include md {
+ @screen md {
      .header {
          display: none; 
      }
  }
```

**Comment by paulhuisman** [comment]
Thanks Adam! Keep up the great work :)
