### ISSUE TITLE
What is the best practice to achieve something like: element element | element>element

### ISSUE THREAD

**Issue by juuyan** [tailwindcss/discuss#334]
I just start with Tailwind and am wondering what is the best practice to achieve something like: element element
element>element
etc.

Use case can be changing a child element's color when the parent gets hovered.

Thanks. And If this something which has got asked, my apologize. I just cant find it. : (

**Comment by adamwathan** [comment]
For your use case I think `group-hover` is what you want 👍 

https://tailwindcss.com/docs/pseudo-class-variants/#group-hover

**Comment by juuyan** [comment]
Thanks @adamwathan ... You saved my day!
Have searched a lot but just could not find it...😭
