### ISSUE TITLE
Question: hidden and block

### ISSUE THREAD

**Issue by nezaboravi** [tailwindcss/discuss#341]
`<div class="bg-red-200 md:w-1/6 md:p-6 hidden md:block md:rounded-l-lg">`

On md screen it shows proper. 
<img width="1232" alt="Screenshot 2019-10-04 18 33 04" src="https://user-images.githubusercontent.com/1515172/66204633-79f48000-e6d5-11e9-9bf1-629a5ea061b2.png">

On mobile on chrome dev tools, does not hide it:
<img width="532" alt="Screenshot 2019-10-04 18 32 25" src="https://user-images.githubusercontent.com/1515172/66204620-719c4500-e6d5-11e9-8eb3-10bda3c55a91.png">

**Comment by tlgreg** [comment]
It's likely just a devtools issue, try it out simply resizing the window.

**Comment by nezaboravi** [comment]
Works fine with resizing the windows, thanks.
