### ISSUE TITLE
Configuration problem of a Typescript/React/Webpack app with Tailwind CSS and PurgeCss

### ISSUE THREAD

**Issue by tuhlmann** [tailwindcss/discuss#342]
I'm trying to setup a project with Typescript/React/webpack/postcss and tailwind.
All works fine as long as I do not include purgeCss in the postcss setup. As soon as I include it, it won't include any classes in the CSS if I do not include *.css files in the content path. If I include *.css it will only include classes from a custom.css I created, but none from tailwind.
Could it be that purgecss does not get passed the full list of tailwind classes? I'm not quite sure what I'm doing wrong, any help would be greatly appreciated!

I created a repo to demonstrate the issue: https://github.com/tuhlmann/tailwind-webpack-postcss

I'm using this webpack snippet to process css module files:

```
          {
            loader: "css-loader",
            options: {
              modules: true,
              localsConvention: "camelCase",
              importLoaders: 1
            }
          },
          {
            loader: "postcss-loader",
            options: {
              sourceMap: false,
              ident: "postcss",
              plugins: [
                require("postcss-import"),
                require("tailwindcss"),
                // require("autoprefixer"),
                // If you comment out the purgecss section, everything works fine.
                require("@fullhuman/postcss-purgecss")({
                  content: ["./src/client/**/*.tsx"],
                  defaultExtractor: content => content.match(/[\w-/:]+(?<!:)/g) || []
                })
                // cssnano()
              ]
            }
          }

```

Thanks!

**Comment by tlgreg** [comment]
PurgeCss looks at the source code of the content file to extract the "words", not an evaluated output.
In your `tsx` file you use camel-cased variants of the class-names, that should be the issue here.
Same case as with string concatenation, which Tailwind's docs warns you about:
https://tailwindcss.com/docs/controlling-file-size#writing-purgeable-html

**Comment by tuhlmann** [comment]
@tlgreg Thank you so much! I saw the camel case strings being found by purgecss (I injected a console.log into the extractor). But that doesn't mean the camel case is found in the css file.

I changed the classes into `className={classnames(styles["large-font"], styles["text-color-blue"], styles["text-blue-800"])}`

And this works beautifully.

I'll see if I can come up with an extractor that adds snake-case words for each camel case found,
that would allow me to use this style of class name.

Thank you again,
Torsten!

**Comment by tlgreg** [comment]
An extractor could be a solution, good idea, "kebabifying" each word found and returning both versions, so the kebab-case version is still matched.
I'm thinking something like this:
```js
const kebabCase = require('lodash/kebabCase')
const extractor = content =>
  (content.match(/[\w-/:]+(?<!:)/g) || []).flatMap(match => [
    match,
    kebabCase(match),
  ])
```

**Comment by tuhlmann** [comment]
Awesome, that does work!

I ended up with this extractor:

```
class TailwindExtractor {
  static extract(content) {
    const matches = content.match(/[A-Za-z0-9-_:/]+/g) || []
    const kebab = matches.map(m => kebabCase(m))
    return matches.concat(kebab).filter((value, index, self) => {
      return self.indexOf(value) === index
    })
  }
}
```

along with this purgeCss config: 
```
                require("@fullhuman/postcss-purgecss")({
                  content: ["./src/client/**/*.tsx", "./resources/public/index.html"],
                  extractors: [
                    {
                      extractor: TailwindExtractor,
                      extensions: ["html", "tsx"]
                    }
                  ]
                })
```

My current config doesn't support Array.flatMap, and I thought I trim the list as early as possible. In my case, just mapping camel to kebab also worked, as long as you don't add camel classes to css. So it seems safer to check both values.

I was initially trying to use https://github.com/sindresorhus/decamelize but that didn't but a dash between letter and number and didn't work for `textBlue800` for instance.

Thanks again!

**Comment by tuhlmann** [comment]
Thanks again @tlgreg !
I updated the repo for reference and close this issue.
