### ISSUE TITLE
 `@apply` cannot be used with `.bg-indigo-dark` because `.bg-indigo-dark` either cannot be found,

### ISSUE THREAD

**Issue by Spartaques** [tailwindcss/discuss#348]
I'm trying to use tailwind on my project but get this error:
 `@apply` cannot be used with `.bg-indigo-dark` because `.bg-indigo-dark` either cannot be found,
My package.json:

`{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.19",
        "bootstrap": "^4.0.0",
        "cross-env": "^5.1",
        "jquery": "^3.2",
        "laravel-mix": "^4.0.7",
        "lodash": "^4.17.13",
        "popper.js": "^1.12",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.20.1",
        "sass-loader": "7.*",
        "vue": "^2.5.17",
        "vue-template-compiler": "^2.6.10"
    },
    "dependencies": {
        "@babel/plugin-syntax-dynamic-import": "^7.2.0",
        "@inertiajs/inertia": "^0.1.6",
        "@inertiajs/inertia-vue": "^0.1.2",
        "autosize": "^4.0.2",
        "install": "^0.13.0",
        "npm": "^6.12.0",
        "nprogress": "^0.2.0",
        "portal-vue": "^2.1.6",
        "postcss-import": "^12.0.1",
        "postcss-nesting": "^7.0.1",
        "tailwindcss": "^1.1.2",
        "vue-meta": "^2.3.1"
    }
}
`

my webpack.mix.js

`const cssImport = require('postcss-import')
const cssNesting = require('postcss-nesting')
const mix = require('laravel-mix');
const path = require('path')
const tailwindcss = require('tailwindcss')

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/js/app.js', 'public/js')
    .postCss('resources/css/app.css', 'public/css', [
        cssNesting(),
        cssImport(),
        tailwindcss('tailwind.config.js'),
    ])
    .webpackConfig({
        output: { chunkFilename: 'js/[name].js?id=[chunkhash]' },
        resolve: {
            alias: {
                'vue$': 'vue/dist/vue.runtime.esm.js',
                '@': path.resolve('resources/js'),
            },
        },
    })
    .babelConfig({
        plugins: ['@babel/plugin-syntax-dynamic-import'],
    });
`

my app.css:
@import "tailwindcss/base"; /* Preflight will be injected here */

@import "tailwindcss/components";

@import "reset";

/* Components */
@import "buttons";
@import "form";
@import "nprogress";

@import "tailwindcss/utilities";

**Comment by adamwathan** [comment]
Like the error says, there is no bg-indigo-dark class in Tailwind.

Here is a list of the classes that do exist:
https://tailwindcss.com/docs/background-color

**Comment by Spartaques** [comment]
I just copied code from another project. Maybe in newer versuon css classes was changed. Thanks
