### ISSUE TITLE
Use tailwind with https://github.com/vuejs-templates/webpack

### ISSUE THREAD

**Issue by jericopulvera** [tailwindcss/discuss#36]
anyone used this with vue webpack? please help

**Comment by m1guelpf** [comment]
Maybe you can add Vue to https://github.com/tailwindcss/webpack-starter

**Comment by jericopulvera** [comment]
I have this vue webpack set up 
https://github.com/jericopulvera/vue-tailwind

But I'm a bit dissatisfied because it only works when I imported it .vue 
<style lang="scss">
```
  @import './assets/sass/app.scss';
</style>
```

I wish I could do it with the same approach in this package https://github.com/vuetifyjs/webpack/blob/master/template/src/main.js
```
import './stylus/main.styl'

new Vue({
  el: '#app',
  render: h => h(App)
})
```

Please help anyone
