### ISSUE TITLE
Flex-Wrap Breaks when adding margin to child elements

### ISSUE THREAD

**Issue by nelsynelz** [tailwindcss/discuss#371]
All, it seems there is an issue with flex-wrap when adding margins. Here is how to repro. 

1. Add this code from the grid example (slightly modified to make width 1/2 on LG): 
```
<template>
    <div class="flex flex-wrap">
        <div class="h-32 w-full lg:w-1/2 mb-4 bg-gray-500"></div>
        <div class="h-32 w-full lg:w-1/2 mb-4 bg-gray-400"></div>
        <div class="h-32 w-full lg:w-1/2 mb-4 bg-gray-500"></div>
        <div class="h-32 w-full lg:w-1/2 mb-4 bg-gray-400"></div>
        <div class="h-32 w-full lg:w-1/2 mb-4 bg-gray-500"></div>
        <div class="h-32 w-full lg:w-1/2 mb-4 bg-gray-400"></div>
    </div>
</template>
```
Then modify it to this: 
```
<template>
    <div class="flex flex-wrap">
        <div class="m-1 h-32 w-full lg:w-1/2 mb-4 bg-gray-500"></div>
        <div class="m-1 h-32 w-full lg:w-1/2 mb-4 bg-gray-400"></div>
        <div class="m-1 h-32 w-full lg:w-1/2 mb-4 bg-gray-500"></div>
        <div class="m-1 h-32 w-full lg:w-1/2 mb-4 bg-gray-400"></div>
        <div class="m-1 h-32 w-full lg:w-1/2 mb-4 bg-gray-500"></div>
        <div class="m-1 h-32 w-full lg:w-1/2 mb-4 bg-gray-400"></div>
    </div>
</template>
```
You'll notice in the first example you'll get 3 rows of 2. In the second example after adding margins you will get 6 rows of 1 that are half width. 

I'm using VueJS and testing this with Sizzy, confirmed same issue in Chrome.

**Comment by adamwathan** [comment]
Margins are added to the outside of an element, so when you have two elements with `w-1/2` and margin on each of them, the total width is greater than 100% causing things to wrap.

Use padding instead of margin:

https://tailwindcss.com/components/grids/#column-spacing

**Comment by nelsynelz** [comment]
Thanks Adam! I figured it was me, which is why I created this in the Discuss section.
