### ISSUE TITLE
Negative margin with prefix Issue

### ISSUE THREAD

**Issue by MicroDreamIT** [tailwindcss/discuss#374]
in `tailwind.config.js`
```
module.exports = {
    theme: {
},
prefix:'tw-'
```

I wanted to apply negative margin but its not working, even class is not found as well.

```
<div class="-tw-mt-10">testing</div>
```
class `-tw-mt-10`, `tw` I have used as prefix

**Comment by adamwathan** [comment]
The class should be `tw--mt-10`, sort of ugly I admit. It's a `tw-` prefix added to the beginning of the `-mt-10` class.

**Comment by MicroDreamIT** [comment]
@adamwathan thanks. I have worked created a similar project but due to lack of gathering contributors its not depreciated. shapecss.microdreamit.com
