### ISSUE TITLE
H1, H2, etc not rendering correct sizes

### ISSUE THREAD

**Issue by invious** [tailwindcss/discuss#378]
![image](https://user-images.githubusercontent.com/1996089/68811686-3cbdcf00-063f-11ea-9a76-ab2ab52fada2.png)

for some reason this CSS is making my headers all very small, and no different in size from each other regardless if it's an H1, or H2, etc

```
h1, h2, h3, h4, h5, h6 {
    font-size: inherit;
    font-weight: inherit;
}
```

**Comment by tlgreg** [comment]
https://tailwindcss.com/docs/preflight#headings-are-unstyled
