### ISSUE TITLE
Font family with all weights available

### ISSUE THREAD

**Issue by sergeByishimo** [tailwindcss/discuss#381]
Hi i'd like to ask what font should we use in order to get all font weights : medium 500, semibold 600, bold : 700, extrabold: 800 and black: 900?

The closest i'm getting is Roboto with font weights 500, 700 and 900.

**Comment by tlgreg** [comment]
There are plenty of fonts that cover most or all from 100-900 font weights.

On one common and free source of fonts: google fonts; You can filter by the number of styles and crank it way up. If a font has 18+ styles it's likely going to be all the weights and their italic versions.
https://fonts.google.com/?stylecount=18&sort=popularity

**Comment by sergeByishimo** [comment]
i spent like the last hour searching and haven't got anything! thanks for the immediate reply!

google fonts gave me Montserrat and it has all weights! thank you very much!!
