### ISSUE TITLE
Horizontal scrolling doesn't work on responsive table UI Tailwind on iOS 

### ISSUE THREAD

**Issue by IsidroMar95** [tailwindcss/discuss#384]
I'm using the responsive tables with horizontal scrolling that Adam [created](https://polished-sunset-0ex44e5cb9xt.tailwindcss.com/components/f0e9baaa-3148-4d4b-b13d-9da241948143) inside another layout he created [Inbox UI](https://polished-sunset-0ex44e5cb9xt.tailwindcss.com/components/198272c2-e9b3-46e5-99da-d0911ad1e07c) and this is the [final result 
](https://tailwind.run/9bKK19).
it's seems works fine in the Tailwind.run app, even in local browser with the responsive tool :
![desktop](https://user-images.githubusercontent.com/23019968/69198782-8d2fa380-0afb-11ea-9d5a-54749b1204f1.gif)

but when i tested on an iPhone 7 and other iOS devices (Safari, Chrome, Firefox) the horizontal scroll doesn't work :
![iphone](https://user-images.githubusercontent.com/23019968/69198837-bcdeab80-0afb-11ea-8699-afc5e5d50c09.gif)
i still dont know why is the problem.

**Comment by exSnake** [comment]
Did you solved this? I had the same problem

**Comment by IsidroMar95** [comment]
I was having the same issue and after looking for the solution I found it (I guess): 
here's my [example](https://codepen.io/isidromar95/pen/abzXvxP) I really hope it works for you
