### ISSUE TITLE
Customization of max-width Not Prevailing

### ISSUE THREAD

**Issue by neilchaudhuri** [tailwindcss/discuss#385]
Here is a snippet of my configuration:

```
fontFamily: {
      sans: [
        "Roboto",
        "Roboto Condensed",
        "Roboto Condensed Bold",
        "Roboto Regular",
        "Oswald",
        "sans-serif"
      ],
      title: ["Oswald", "sans-serif"],
      accent: ["Oswald", "sans-serif"]
},
maxWidth: {
    xs: '20rem',
    sm: '24rem',
    md: '28rem',
    lg: '32rem',
    xl: '36rem',
    '2xl': '42rem',
    '3xl': '48rem',
    '4xl': '56rem',
    '5xl': '64rem',
    '6xl': '72rem',
    full: '100%',
    'abcde': "22rem"
}
```

My font customizations are producing custom styles I can use, but the same isn't happening for `max-width` with my dummy `abcde` entry. Besides the above, I have experimented with `abcde` on its own,  `abcde` as part of the `extensions` block, and other variations to no avail.

Please let me know if there is something special related to `max-width` or if I am doing something silly.

**Comment by neilchaudhuri** [comment]
What's odd also is that if I remove everything but `abcde`, I get CSS that looks like the default as if I made no configuration changes at all.

In other words, given this:

```
maxWidth: {
    abcde: "22rem"
}

```
I get this:

```
.xs\:max-w-xs {
    max-width: 20rem !important;
  }

  .xs\:max-w-sm {
    max-width: 24rem !important;
  }

  .xs\:max-w-md {
    max-width: 28rem !important;
  }

  .xs\:max-w-lg {
    max-width: 32rem !important;
  }

  .xs\:max-w-xl {
    max-width: 36rem !important;
  }

  .xs\:max-w-2xl {
    max-width: 42rem !important;
  }

  .xs\:max-w-3xl {
    max-width: 48rem !important;
  }

  .xs\:max-w-4xl {
    max-width: 56rem !important;
  }

  .xs\:max-w-5xl {
    max-width: 64rem !important;
  }

  .xs\:max-w-6xl {
    max-width: 72rem !important;
  }
```

**Comment by adamwathan** [comment]
Hmm it should work, here's a working example:

https://tailwind.run/MJBedv

Are you sure your config file is actually being used? Can you share a GitHub repo that reproduces the issue?

**Comment by neilchaudhuri** [comment]
I had the same thought because I wouldn't put it past myself to do something absurd. But I tried different things like removing breakpoints, and predictably the output file size got much smaller. So it seems the file file is being used.

I will look into reproducing the issue elsewhere.

**Comment by neilchaudhuri** [comment]
And as we surmised, I did something absurd. I placed the `maxWidth` configuration near the bottom of my file and, unbeknownst to me, outside the theme object. This is why the config didn't take. 

The lesson is to eat more fish and gingko to be smarter.
