### ISSUE TITLE
SonarQube

### ISSUE THREAD

**Issue by josephzidell** [tailwindcss/discuss#387]
My project is integrated with [SonarQube](https://www.sonarqube.org/), a popular static analysis code checker. Running tailwind through it indicates it doesn't understand the directives. 

![image](https://user-images.githubusercontent.com/1812443/69484759-206f1e80-0e05-11ea-9c31-d548397ace94.png)

![image](https://user-images.githubusercontent.com/1812443/69484779-53191700-0e05-11ea-8ae2-daf97b1e6a8c.png)

How would you handle this?

**Comment by hacknug** [comment]
Would using `.pcss` as your file extension solve the issue? If not you might be able to configure SonarQube's listing features. Maybe they'll use your Stylelint config to decide what is an issue and what is not?

**Comment by josephzidell** [comment]
@hacknug The extension change worked. Thanks!
