### ISSUE TITLE
Tailwind CSS and create-react-app

### ISSUE THREAD

**Issue by ptmdmusique** [tailwindcss/discuss#389]
Hi Tailwind Team,

First, I would like to say thank you for the great framework that you guys are working on here!
While trying to follow [this ](https://blog.logrocket.com/create-react-app-and-tailwindcss/) to get Tailwind CSS to work with my newly created React app, I got `Unknown Property Error` in Chrome Inspector when using directives such as @apply. However, I tried to use Tailwind with NextJS framework before and it worked perfectly fine. 

I read on some articles and some of them discuss about changing webpack config file, but since I'm using `create-react-app`, I don't think I have such ability unless I eject it. 

Would you guys help me with this issue? Thank you very much!

**Comment by hacknug** [comment]
Haven't used it myself but this might be helpful: https://github.com/gsoft-inc/craco

**Comment by ptmdmusique** [comment]
> Haven't used it myself but this might be helpful: https://github.com/gsoft-inc/craco

Lemme try it out, have you got issue with directive like this before?

**Comment by hacknug** [comment]
> Lemme try it out, have you got issue with directive like this before?

No, sorry. I don't usually work with React.

> I wonder what actually makes the directives work with css

What makes it work is PostCSS. Tailwind is _only_ a plugin that tells PostCSS how to transform that CSS-like syntax into something else. Make sure you're telling Webpack or whatever you use to process your CSS that it should take care of those files. You'll probably have something setup to run Autoprefixer on your CSS so Tailwind should run before it.

**Comment by ptmdmusique** [comment]
> > Lemme try it out, have you got issue with directive like this before?
> 
> No, sorry. I don't usually work with React.
> 
> > I wonder what actually makes the directives work with css
> 
> What makes it work is PostCSS. Tailwind is _only_ a plugin that tells PostCSS how to transform that CSS-like syntax into something else. Make sure you're telling Webpack or whatever you use to process your CSS that it should take care of those files. You'll probably have something setup to run Autoprefixer on your CSS so Tailwind should run before it.


You're right, I fixed it by ejecting webpack configuration using the package similar to what you sent me. I also used [this ](https://medium.com/@harryhedger/quick-how-to-setup-tailwind-with-create-react-app-6e7af96ad32c) tutorial. 

Closing this for now. Thanks a lot for the help!
