### ISSUE TITLE
Tailwind Examples

### ISSUE THREAD

**Issue by davidpiesse** [tailwindcss/discuss#40]
Hi  @adamwathan & Co,

I know you are working on examples, below is my conversion of the first Bootstrap Example.

Firstly is this the place to suggest such things?

Secondly - how the heck do I get that button to size the same as the button without custom padding spacing 😈   (Please ignore if not appropriate here)
![Input != Button](https://user-images.githubusercontent.com/800650/32516660-ff968f18-c3fb-11e7-83c6-9052c11a9fa6.png)

Happy to build more if you want to offload some effort from the core team.

[Gist](https://gist.github.com/davidpiesse/8e7a33b7eaeb2b28887aba55a4d901d8)

![Screenshot](https://user-images.githubusercontent.com/800650/32516590-b8fedd44-c3fb-11e7-893c-9a48b4633c8f.png)

**Comment by adamwathan** [comment]
Hey @davidpiesse! Yeah we are working on more examples for sure, including fully fleshed out full page examples of fake apps 👍 

I don't think we want to include Bootstrap's example in the actual documentation but I think it's cool to have it replicated here in the discussions for anyone interested for sure.

There's two ways to handle that height issue...

1. Make sure the text size and line height are the same in both the button and the input:

    https://jsfiddle.net/gk2oonns/1/

2. Use flexbox to make both items stretch vertically, so the shorter one matches the height of the taller one:

    https://jsfiddle.net/aq7bkgxm/

Hope that helps! Sorry just running out the door so don't have time to elaborate on the specific changes, but it's all in the fiddles 👍

**Comment by davidpiesse** [comment]
Awesome,
I will investigate and thanks for the effort; it is very much appreciated!
Looking forward the the fleshed out apps, saw the Twitter one and was mightily impressed with the outcome of a no CSS look!
:)
