### ISSUE TITLE
'max-w-screen-xl' missing

### ISSUE THREAD

**Issue by nicktc** [tailwindcss/discuss#409]
Hi,

I am playing for the first time with Tailwindcss in combination Sapper (not sure if relevant). In the Tailwindcss documentation the header has a class class 'max-w-screen-xl'. That class doesn't exist in my generated index.css. This is my tailwind.js file:

module.exports = {
  theme: {
    extend: {}
  },
  variants: {},
  plugins: []
}

So based on the defaultConfig on Tailwindcss this should all work. Not sure what I am missing here.

Thanks,

Nick

**Comment by tlgreg** [comment]
[It's a custom value.](https://github.com/tailwindcss/docs/blob/8fa1fc6f346efff0add61c2b4ec9ccffb18f3cae/tailwind.config.js#L46)

**Comment by nicktc** [comment]
Thanks!
