### ISSUE TITLE
How to make full-width container, like bootstrap's `container-fluid`?

### ISSUE THREAD

**Issue by mikebronner** [tailwindcss/discuss#41]
I've been reading the documentation, and am struggling to get a container to be full-width. I have tried the following:

```html
        <div class="container w-screen mt-4">
            <div class="bg-blue-lightest border-l-4 border-blue text-blue-dark p-4"
                role="alert"
            >
                <p class="font-bold">Oops!</p>
                <p>No images have been added yet. Please check back soon!</p>
            </div>
        </div>

        <div class="container w-full mt-4">
            <div class="bg-blue-lightest border-l-4 border-blue text-blue-dark p-4"
                role="alert"
            >
                <p class="font-bold">Oops!</p>
                <p>No images have been added yet. Please check back soon!</p>
            </div>
        </div>
```

Is the solution here to drop the container, and do something like this?

```blade
    <div class="w-screen mt-4"> <!-- instead of container-fluid here -->
        @forelse ($images as $image)
            <img class="sm:1/2 md:1/4 lg:1/8 xl:1/12"
                src=""
            >
        @empty
            <div class="container mx-auto">
                <div class="bg-blue-lightest border-l-4 border-blue text-blue-dark p-4"
                    role="alert"
                >
                    <p class="font-bold">Oops!</p>
                    <p>No images have been added yet. Please check back soon!</p>
                </div>
            </div>
        @endforelse
    </div>
```

Sorry for my newb question :) just started diving into it and am working on wrapping my head around the concepts and opinions this frameworks works under. :)

**Update:** added comment in code to clarify where I was looking to make full-width. Sorry for the confusion.

**Comment by HelgeSverre** [comment]
bootstrap's ```container-fluid``` is basically just left-right padding and margin right-left auto.
the container in tailwind just sets the width/max-width.
replace ```.container``` with ```.mx-auto px-2``` (2 or whatever to add left-right padding) and I think you'll get the result you'e looking for.

**Comment by mikebronner** [comment]
Right now I am using `w-screen mt-4` instead of `container` to achieve the full-width effect. I like your use of `mx-auto` better though, as it is more versatile and will likely take padding and margins into account, whereas `w-screen` will always be 100% no matter what. Thanks!

**Comment by adamwathan** [comment]
Just to follow up on what @HelgeSverre said, any `div` is going to be full width by default unless you've changed the width explicitly.

Here's Bootstrap's `container-fluid` styles:

```
.container-fluid {
  width: 100%;
  padding-right: 15px;
  padding-left: 15px;
  margin-right: auto;
  margin-left: auto;
}
```

Since block level elements are already full width by default, I honestly don't understand why they are defining `width: 100%` or `margin-{side}: auto`; auto margins won't do anything on an element that's full width.

So to create a container that works like `container-fluid`, all you really need is horizontal padding:

```
<div class="px-4">
  ...
</div>
```

You shouldn't need `w-screen` unless you are nested inside a smaller element and need to break out of it for one reason or another 👍

**Comment by mikebronner** [comment]
Thanks for the clarification on `w-screen`! :)

**Comment by Shoulao** [comment]
After a few years.. maybe someone will need this :P
.container class has limitation of max-width, you need to simply add an additional class to this element and set the max-width to 100%. 

Works! :)

**Comment by Esporia** [comment]
@Shoulao So simple ! Thanks
```
.container {
    max-width: 100%;
}
```

**Comment by Shoulao** [comment]
:)

**Comment by mrjonwilson** [comment]
Hi @Esporia and @Shoulao! Where do I add that?

`.container {
    max-width: 100%;
}`

I am building a site with this Gatsby starter and wanting to make the content area full width: https://github.com/netlify-templates/gatsby-starter-netlify-cms

**Comment by Shoulao** [comment]
There is a .container class in bootstrap. `Container > Row > Col` 

Container class/element has a limitation of max-width. You can simpy open Chrome Dev Tool, select element and check if certain element has `max-width` position - if so, just add an additional class to that element with `max-width: 100%`. This should override bootstrap class.

1. 
`.container { max-width: 100%; }`
2. 
`.additionalClass.container { max-width:100% ; }`

ProTip: The best way to see what's wrong is to open Dev Tool in browser, and check which element has  huge margins. max-width limitation.

**Comment by mrjonwilson** [comment]
Oops! I shared the wrong github repo! This is the one I am using: https://github.com/Oddstronaut/gatsby-starter-tailwind

I am using TailwindCSS, not bootstrap.

**Comment by Shoulao** [comment]
Well, I think here you have a limitation of 56 rems. And the class name.

<img width="1440" alt="Zrzut ekranu 2019-06-29 o 20 29 40" src="https://user-images.githubusercontent.com/28606968/60388073-bac47380-9aac-11e9-90f2-60161fb93882.png">

**Comment by mrjonwilson** [comment]
NIce! Found it! I changed
`flex flex-col flex-1 md:justify-center max-w-4xl mx-auto px-4 py-8 md:p-8 w-full`
to
`flex flex-col flex-1 md:justify-center w-full`

Thanks!

**Comment by Shoulao** [comment]
No problemo!  @mrjonwilson  :)

**Comment by EricMiulli** [comment]
In the bootstrap.css file add the following code:

@media (min-width: 1920px) {
    .container {
        width: 1850px;
    }
}

Set size for each media type i.e. phone, tablet, monitors.

**Comment by heshamelmasry77** [comment]
I guss `w-full` does the job

 ```
<div class="w-full">
    <header>
      <NavBar/>
    </header>
    <main>
      <slot/>
    </main>
    <footer></footer>
  </div>
```
thats my example
