### ISSUE TITLE
Top and right missing with absolute

### ISSUE THREAD

**Issue by jaydubyasee** [tailwindcss/discuss#410]
I have the following

`<div class="flex relative">`
`<div class="absolute top-0 right-0 -mt-16 text-xl">Retrieving control</div>`
`</div>`

Everything is working okay except for right and top which are missing from the css. I have no idea how to start investigating the problem.

**Comment by nezaboravi** [comment]
Are you using purgeCss? IF so, maybe is stripped?

**Comment by jaydubyasee** [comment]
Tried it with and without purgeCSS with no difference.

**Comment by jaydubyasee** [comment]
Found the problem. Turns out I had overridden the inset in my tailwind config when I meant to extend it!
