### ISSUE TITLE
Unable to npm install TailwindCSS on my Glitch site.

### ISSUE THREAD

**Issue by cmarabate** [tailwindcss/discuss#446]
I'm fairly new to Glitch but I'm pretty sure I did what I was supposed to. I Added the TailwindCSS package using "Add Package" in my package.json and then used the console glitch gives me for my site and used the "npm install tailwindcss" command. It gave me some errors telling me I needed to update some packages manually, so I went through and updated all the ones it told me to and then ran the "npm install tailwindcss" command again. This time it didn't show any errors but nothing appears to have been added to my sites files anywhere that I can see at-least. I also added all the @tailwind directives into one of my css files & I have some of your example code on the site, so I can tell that it is not using Working.

Is there something that I am missing?

**Comment by tlgreg** [comment]
There is nothing really specific to tailwindcss what you would need to do on glitch.
Don't forget if you use the console to change files / install dependencies restart the container with console command `refresh`.
Created a quick example with `vue-cli` here:
https://glitch.com/~juvenile-taxi-ixp0cx8dcp

**Comment by cmarabate** [comment]
I tried using refresh but it didn't seem to do anything, maybe it is an issue with my Glitch install or something. Sorry to bother you, I probably should have contacted them instead.

I really appreciate you creating a quick example for me but it doesn't seem to be working...
![image](https://user-images.githubusercontent.com/12236062/74673163-b7394600-517c-11ea-80eb-9ae1fdaa1621.png)

It would be great to have a working example for me to play around with.

Thanks!

**Comment by tlgreg** [comment]
It's some `@vue/cli` - `pnpm` issue, had to switch the container to normal `npm`, unrelated to `tailwindcss`.
When I created it I run `npm i` from the console, so it worked then, but I believe `enable-npm` command persists across restart, so it should work from now on.

<details><summary>screenshot</summary>

![chrome_BNi0CIKjZk](https://user-images.githubusercontent.com/666791/74684171-7e748d80-51cb-11ea-8e03-976f8800dd5a.jpg)

</details>

**Comment by tlgreg** [comment]
If I clone the [playground](https://github.com/tailwindcss/playground) that also just works. The `playground` is just static html served with `live-server` and the css is compiled with `postcss-cli`.
Example: https://glitch.com/~tailwindcss-playground-6
Did nothing, just cloned from github.

**Comment by cmarabate** [comment]
This is perfect, thanks!
