### ISSUE TITLE
Collecting Tailwind CSS demos & examples

### ISSUE THREAD

**Issue by nechita** [tailwindcss/discuss#45]
Hey guys,

First of all, I'm very happy to see so many people trying out Tailwind and trying to create prototypes, demos, clones and even redesigning entire websites using the framework.

I've been very active in researching utility css frameworks for my own use in the past few months, before Tailwind was actually launched. 

After the launch of Tailwind I decided I should try and collect as many Tailwind demos & examples as possible, and also, start a snippets library, because people will start searching a lot on Google for examples, and it wouldn't hurt to stumble upon an organized set of resources.

Yesterday I launched https://tailwindexpo.com/ and already collected a few examples.

Do you have more demos & examples you want to be featured in TailwindExpo? 

If so, please DM or @ [me on Twitter](https://twitter.com/NechitaGabriel) and let me know.

PS: I hope the makers of Tailwind don't mind me creating this website, if there's any issue with it, just [DM me](https://twitter.com/NechitaGabriel) and let me know. I'm not in any way affiliated with the makers, just extremely enthusiast about the framework.

**Comment by psren** [comment]
Just for reference. #22

**Comment by nechita** [comment]
Thanks. Not sure how I missed that thread

**Comment by m1guelpf** [comment]
@nechita There is already a [awesome-tailwind](https://github.com/merchedhq/awesome-tailwindcss) list, maybe we could join the two projects into one by using the list as a CDN?

**Comment by nechita** [comment]
@m1guelpf let's take this privately and see what happens :P

**Comment by DiegoArrieta** [comment]
all offline :(

**Comment by hacknug** [comment]
@DiegoArrieta check https://builtwithtailwind.com/
