### ISSUE TITLE
Why do only min-w-0 and min-w-full exist and not i.e. min-w-24?

### ISSUE THREAD

**Issue by ChristianHuff-DEV** [tailwindcss/discuss#450]
I am trying to create a button that has the following behaviour:

- The button should always be at least `6rem` wide
- If `6rem` is to small for it's text, the button should grow to fit the text

Using a mix of regular CSS and Tailwind the following achieves what I want:
```html
<button style="min-width: 6rem" class="w-auto">Text to long for 6 rem</button>
```
This button is always at least `6rem` wide but will grow with the content if required.

Why is there no `min-w-24` class? And/Or is there another way to achieve the desired result with only using Tailwind?

**Comment by adamwathan** [comment]
You can add those values to your config if you'd like to have them there 👍🏻

**Comment by ChristianHuff-DEV** [comment]
@adamwathan Thank you for the tip. I found the [documentation](https://tailwindcss.com/docs/adding-new-utilities/).

I expected the following to work:

```vue
<template>
  <button class="bg-blue-500">
    <slot></slot>
  </button>
</template>

<script></script>

<style scoped>
button {
  @apply min-w-24;
}
</style>
```

But I'm getting the following error:
```
ERROR in ./src/components/base/QButton.vue?vue&type=style&index=0&id=db38a996&scoped=true&lang=css& (./node_modules/css-loader/dist/cjs.js??ref--4-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--4-2!./node_modules/vue-loader/lib??vue-loader-options!./src/components/base/QButton.vue?vue&type=style&index=0&id=db38a996&scoped=true&lang=css&)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(11:3) `@apply` cannot be used with `.min-w-24` because `.min-w-24` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.min-w-24` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

   9 | 
  10 | button {
> 11 |   @apply min-w-24;
     |   ^
  12 | }
  13 | 
```

My css file:

```css
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";

.min-w-24 {
  min-width: 6rem;
}
```

When adding the class directly to the element it works. But I would like to avoid that since depending on a prop (stripped from the example above) I want to apply different classes.

**Comment by adamwathan** [comment]
The problem is that with tools like Vue, all of your style blocks are processed completely independently so when Tailwind tries to apply `min-w-24` it fails because it can't "see" that class since it's defined in a separate file and Vue is running PostCSS in complete isolation against your component.

The correct way to add that value is using your Tailwind config file, then it will work:

https://tailwindcss.com/docs/min-width#customizing

The "Adding new utilities" docs is geared towards adding new _custom_ utilities, for CSS properties we don't support out of the box. For classes we already have, all you need to do is add your missing values to your Tailwind config file:

```js
// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      minWidth: {
        '24': '6rem',
      },
    },
  },
}
```

**Comment by ChristianHuff-DEV** [comment]
Awesome. Thanks for you help!
