### ISSUE TITLE
% of vh?

### ISSUE THREAD

**Issue by 8brandon** [tailwindcss/discuss#451]
Hi there, 

Loving Tailwind, it's my first day using it.

I only see a class for making something 100vh, but what about a % of vh? 
I sometimes build my views with 90vh for example.

**Comment by adamwathan** [comment]
You can add those values to your config if you need them 👍🏻 

https://tailwindcss.com/docs/min-height/#customizing

**Comment by 8brandon** [comment]
Thanks Adam!
