### ISSUE TITLE
Non-Flexbox Responsive Grid

### ISSUE THREAD

**Issue by filljoyner** [tailwindcss/discuss#47]
Hi all,
First off, thanks so much for your work here!

Are there any plans to add a responsive grid to Tailwind CSS that does not use Flexbox? Flexbox is the future but out of reach for many corporate clients that lag behind current tech. The answer is likely no, and I'd complete understand that, but thought I'd ask.

Thanks!
Phil

**Comment by adamwathan** [comment]
Hey @filljoyner! We don't have plans to add a higher level float-based grid component like that to core *BUT* we are working on a plugin/extension system that would make it super easy to pull in a grid like that built on top of Tailwind. Look for that in the near-ish future!

Now all *that* said, it's totally do-able to build a non-flexbox grid with existing Flexbox utilities; you'll just be a bit closer to the metal:

https://jsfiddle.net/r0nwjL34/1/

**Comment by filljoyner** [comment]
Thanks @adamwathan! The sample was super helpful. We'll give that a go on an upcoming build. If all else fails we'll roll our own for a bit and then give the extension system a look when it comes out. I'm really digging the syntax and integrate, if we decide to build our own, with a plugin/extension system sounds awesome.

Hopefully in another 3-ish years, we won't have to worry about floating grid systems.
