### ISSUE TITLE
Class .-translate-y-1/2 is not working

### ISSUE THREAD

**Issue by GlennvdSteen** [tailwindcss/discuss#472]
I am using class .-translate-y-1/2  on an element but it's not working. Chrome outputs this CSS: 
<img width="243" alt="Screenshot 2020-03-02 at 14 06 10" src="https://user-images.githubusercontent.com/47741983/75678941-fee8c300-5c8e-11ea-91a8-a352109e0f58.png">

I am using Tailwind 1.2.0. Someone has the same issue or am I doing something wrong?

**Comment by adamwathan** [comment]
Have you added the `transform` class as well?

https://tailwindcss.com/docs/translate/#usage

**Comment by GlennvdSteen** [comment]
@adamwathan , thanks for your reply! Don't know why I did not see this, it's working now 👍
