### ISSUE TITLE
Gutters and documentation

### ISSUE THREAD

**Issue by javi-dev** [tailwindcss/discuss#49]
I shamelessly admit that CSS is not my forte, and its "hacks" even less than that.

I've spent quite a bit of time trying to make gutters work on a form I was working on, and I couldn't figure, for the life of me, why they weren't working. Ok, so I have to make this flex, and add a negative margin for some reason. The bottom items… nah, I'm good, I already have the width I want, and _I don't want padding_, let's try it. What the…

After dom inspecting, colorful cursing and creative googling "flex negative margin thingy", I understood how the "hack" worked _(I know it's not a hack)_.

What I'm trying to get at here is that maybe it could be clearer in the docs that you have to use the same padding as the negative margin, maybe a short note or highlighting the number 4, we'll figure it out.

Just in case someone comes searching for it in the future, probably me in a few ~~weeks~~ days, **you have to make the negative margin the same as the horizontal padding**.

**Comment by adamwathan** [comment]
Yeah the grid page is currently a super quick hack job, I plan to write real documentation around creating your own grids in the near future.

**Comment by javi-dev** [comment]
The documentation is amazing in its current state, even if it's clearly a WIP, like it's stated over and over. In the meantime, I hope someone somewhere finds this thread useful.

**Comment by javi-dev** [comment]
And with today's documentation face-lift, I can close this issue now. Thanks!
