### ISSUE TITLE
Licensing details

### ISSUE THREAD

**Issue by olakara** [tailwindcss/discuss#5]
Hi,
 I noticed that there is no mention of any Licensing for tailwindcss. Would like to have some light in this area.. just curious!!

**Comment by reinink** [comment]
Hey there!

The licence can be found in the `package.json` file. It's just MIT.

https://github.com/tailwindcss/tailwindcss/blob/master/package.json#L5

Hope that helps. :)

**Comment by joshmanders** [comment]
For better visibility I created a PR adding a `LICENSE` file. https://github.com/tailwindcss/tailwindcss/pull/36
