### ISSUE TITLE
Prefixing generated classes names with a custom string

### ISSUE THREAD

**Issue by mustafaaloko** [tailwindcss/discuss#51]
Is there a way to prefix or alter the generated classes names while building the output CSS file? For example, if I do below:

```
./node_modules/.bin/tailwind build style.css -o output.css --prefix-class="my-tailwind-"
```

And the classes names would be generated like `my-tailwind-container`, `my-tailwind-text-center`, `my-tailwind-bg-red` and etc.

I think this will help using Tailwind with other frameworks and avoids any conflicts with them. Maybe I am wrong, please let me know what you think.

**Comment by MichaelDeBoey** [comment]
@adamwathan is making a @prefix at-rule in tailwindcss/tailwindcss#100 🙂

**Comment by mustafaaloko** [comment]
@MichaelDeBoey awesome, thank you, closing this.
