### ISSUE TITLE
How to handle item offsets in flex grids?

### ISSUE THREAD

**Issue by mikebronner** [tailwindcss/discuss#54]
I am trying to achieve something like Bootstrap's `offset` utility classes, particularly useful in horizontal forms where an element doesn't have a label, for example. Any thoughts on how to achieve that here? I would like to avoid inserting dummy divs or spans to deal with it. (They serve no semantic purpose, and therefore should not be part of the DOM.)

I was thinking that utility classes along the lines of `.ml-1/3` and `.pr-1/4` would be nice, but I do understand that those add can add quite a bit of overhead?

**Comment by adamwathan** [comment]
Hey Mike, for simple cases you can handle this with either auto margin utilities or justify content utilities. Here are quick examples of both:

[Using auto margin utilities](https://jsfiddle.net/3xogyqbn/1/)

[Using justify content utilities](https://jsfiddle.net/azc4tmfg/1/)

These won't handle really complex situations with many columns in a row, but they should be enough for common use cases. Let me know how that works for you!

**Comment by mikebronner** [comment]
oh, of course!! haha, forgot about the aligning features of the `auto` classes. Thanks for the reminder, that should work perfectly!

**Comment by aaronmoodie** [comment]
For anyone looking for a little more, these are some utility classes I did up for offset on a 12 column grid.

```
@responsive {
  .push-0 {
    margin-left: 0;
  }
  .push-1\/2 {
    margin-left: 50%;
  }
  .push-1\/3 {
    margin-left: 33.3333333333%;
  }
  .push-2\/3 {
    margin-left: 66.6666666666%;
  }
  .push-1\/4 {
    margin-left: 25%;
  }
  .push-3\/4 {
    margin-left: 75%;
  }
  .push-1\/6 {
    margin-left: 16.6666666667%;
  }
  .push-1\/12 {
    margin-left: 8.3333333333%;
  }
  .push-5\/12 {
    margin-left: 41.6666666667%;
  }
  .push-7\/12 {
    margin-left: 58.3333333333%;
  }
  .push-11\/12 {
    margin-left: 91.6666666667%;
  }
}
```

**Comment by jmp909** [comment]
Hi, I've raised this here (didn't realise this discussion site existed)
https://github.com/tailwindcss/tailwindcss/issues/632

i've been using inuitcss previously and needed to use its responsive push/pull column offset classes on the last 3 projects I've done, so yes it would be great to see some implementation of this like @aaronmoodie posted above

as mentioned something like this would be useful
```css
.u-pull-1/6@tablet
.u-push-1/4@desktop
.u-push-reset@wide
```

so in terms of tailwind syntax maybe eg 
`md:pull-1/6 lg:push-1/4`

**Comment by jmp909** [comment]
just leaving the info for anyone looking. this is essentially doable with the margin/negativeMargin in the config file

( @aaronmoodie )

`negativeMargin: { ... '1/6': '16.6666666667%' }`

then

`class="lg:-ml-1/6"` (instead of a custom pull class for eg `lg:pull-1/6`)
