### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by benface** [tailwindcss/discuss#56]
I cannot find a changelog anywhere. Surely this would be helpful, especially when there are breaking changes (e.g. removed/modified classes) between versions?

**Comment by adamwathan** [comment]
Hey @benface! We haven't had any breaking changes yet, but everything is always documented on the [releases page](https://github.com/tailwindcss/tailwindcss/releases).

We'll add a real changelog to the docs eventually too.

**Comment by benface** [comment]
@adamwathan Oh, I don't know how I missed that! Good to know, thank you. :)
