### ISSUE TITLE
 atRule.before is not a function

### ISSUE THREAD

**Issue by ar-stackrox** [tailwindcss/discuss#59]
@adamwathan 

I tried running tailwind but get the following error -  

```
atRule.before is not a function
```

I searched for this error in the repo issues, but none of the fixes apply to me. I'm not using Laravel Mix and I'm on PostCSS 6.0.14 (latest). I did a reinstall of my NPM packages and all.

I have a Gulp function that looks like this and a task that runs this function -

```
function tailwind() {
    return gulp.src(path.join(HOME.source, "/scss/app2.css"))
      .pipe($.postcss([tailwindcss("./tailwind.js")]))
      .pipe(gulp.dest("./src/static/css"));
}


gulp.task("css", gulp.series(tailwind)); 
```

my tailwind config is the default generated from the CLI, and my app2.css looks like - 

```
@tailwind preflight;

@tailwind utilities;
```

Any ideas? Thanks!

**Comment by maximilianschmitt** [comment]
Hi @ar-stackrox, did you solve this issue? I'm having the same problem.

Thanks for your help!

**Comment by ar-stackrox** [comment]
Ah yes, I just had to update to the latest PostCSS version I believe. I had my version locked to 5.x, but got mixed up. I updated postCSS but needed to update gulp-postcss @maximilianschmitt

**Comment by maximilianschmitt** [comment]
Thanks for the quick reply @ar-stackrox! That was it, I was using an old PostCSS version. Thanks! :)
