### ISSUE TITLE
.container => affects the bootstrap grid

### ISSUE THREAD

**Issue by jsgcode** [tailwindcss/discuss#62]
Hello good Morning.
Normally I use grid systems of third party rulers. I have had problems with the ".container" class native to tailwind.
I already solved them (with hacks), I comment this in case someone else experiences something similar. Maybe they can find an "official" solution for it, like moving it to a separate module, rename it, or something.
Greetings to all.

**Comment by adamwathan** [comment]
Tailwind isn’t currently designed to work on top of Bootstrap; there’s lot of classes that will collide. In 0.2 coming out today or Monday though it will be possible to set a custom prefix for all of Tailwind’s classes.

**Comment by adamwathan** [comment]
Closed by mistake, fat thumbs 😄

**Comment by psren** [comment]
> there’s lot of classes that will collide. 

I don't think that *lot* of classes will colide.
Most tailwind-classes are utilities. Mostly classes named after the property they adjust.

If they collide an other framework would be stupid to choose an other value for the same class, or the user can decide which one should be loaded later.

As far as I can see problematic classes are only:

- .container
- .truncate
- .pin{-x|-y}

and it seems like .container is the only class that collides with bootstrap.
The problem can be solved by the Plugin system (see https://github.com/tailwindcss/tailwindcss/issues/107) in my opinion?

**Comment by jsgcode** [comment]
I see, for the time it takes the project I thought it would be the first to report it. An apology. In effect, I have the same problem that was commented. I do not know how hard it would be, but the idea of disable utilities individually is very good. Or even, individually choose which utilities should be prefixed, so you do not have to use prefixes in all utilities, just for a few that cause conflict.
In any case they are minimal problems, a little tedious but just that. We can wait until the best solution is found. Surely with time will come to light more details that allow to refine Tailwind.

**Comment by rgaufman** [comment]
I'm trying to use tailwind 1.0.3 on top of bootstrap 4.3.1 and some styles seem to be affected like dropdown shadows. Is there any solution to this?

**Comment by hacknug** [comment]
> I'm trying to use tailwind 1.0.3 on top of bootstrap 4.3.1 and some styles seem to be affected like dropdown shadows. Is there any solution to this?

Like Adam mentioned, you can set a prefix for your Tailwind-generated classes: https://tailwindcss.com/docs/configuration/#prefix
