### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by alighasemzadeh** [tailwindcss/discuss#64]
Hello,
I would like to know any plan for RTL support?

**Comment by ybaruchel** [comment]
+1

**Comment by hacknug** [comment]
What kind of things you need to do differently to support RTL languages? Would a plugin adding these classes be enough? https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Writing_Modes

**Comment by Dahdoul** [comment]
+1

**Comment by ybaruchel** [comment]
It can be done using a package like this one [here](https://anasnakawa.github.io/bi-app-sass/) but unfortunately we should rewrite the whole framework.

**Comment by Dahdoul** [comment]
@ybaruchel I ended up overriding directional styles for example: padding-left to padding-right and ...ETC

**Comment by ybaruchel** [comment]
@Dahdoul I Did the same thing, I wish they had RTL support out of the box.

Note that sometimes you will find yourself using a lot of `unset` and `!important` :/

**Comment by AhmedFawzy** [comment]
@Dahdoul @ybaruchel So is there any plans to share what you did to help others and of-course this will help with contribution

**Comment by ybaruchel** [comment]
@AhmedFawzy I just patched the selectors used by my specific app.. It can take forever to change the whole framework :/

**Comment by adamwathan** [comment]
Someone mentioned creating a custom variant for RTL stuff on Twitter, maybe worth looking at:

https://twitter.com/patrikengborg/status/1047802931343499264

You'd have to enable the [variant plugins experiment](https://github.com/tailwindcss/tailwindcss/releases#registering-new-variants-from-plugins) in your config file first, then add that function to your plugins.

By the sounds of it, it would let you do stuff like this:

```html
<html dir="rtl">
<!-- ... -->
  <p class="text-left rtl:text-right">...</p>
<!-- ... -->
</html>
```

**Comment by RonMelkhior** [comment]
I actually created a Tailwind plugin to do this for LTR and RTL a few days ago using the variant plugin API. Feel free to use it!

https://github.com/RonMelkhior/tailwindcss-dir

**Comment by AhmedFawzy** [comment]
seems promising Thanks @adamwathan @RonMelkhior

**Comment by acrolink** [comment]
This issue should be prioritized.

**Comment by adamwathan** [comment]
I recommend using the plugin @RonMelkhior linked to above:

https://github.com/RonMelkhior/tailwindcss-dir

No concrete plans to add this to core right now as I have never built an RTL site personally, so I am not the best person to implement or maintain such a feature. Thankfully we have a plugin system so it's very straightforward to augment Tailwind with functionality like this yourself if you need it.

**Comment by khanriyaz24** [comment]
> https://github.com/RonMelkhior/tailwindcss-dir

Thank you Bro, It's work like a charm.
