### ISSUE TITLE
A tag with no styles class or change color of the a tag on parent hover

### ISSUE THREAD

**Issue by nathan6137** [tailwindcss/discuss#67]
I have the following html setup:

parent div (row) has classes `hover:bg-purple hover:text-white`
all columns work except for one that contains an `a` tag.

The reason is because `a` tag has default browser styles. Is there something similar to `appearance-none` that can be applied to the `a` tag to achieve a clean slate? 

If not how would i go about changing color of an `a` tag when hovering over the parent row?

**Comment by adamwathan** [comment]
You could create a class like this:

```
.text-inherit { color: inherit; }
```

...and add that the `a` tag. Could add it to your color scale as well if you wanted so it was generated by Tailwind. See if that gives you the results you're expecting 👍

**Comment by nathan6137** [comment]
That works, thanks! maybe it should be added to the utilities just as `appearance-none`
👍👍👍

**Comment by vintprox** [comment]
It looks like a good addition to Tailwind CSS, since many developers tend to make links colored by inhertiance!
