### ISSUE TITLE
Upgrading TailwindCSS

### ISSUE THREAD

**Issue by pxwee5** [tailwindcss/discuss#78]
I just upgraded Tailwind from v0.2.2 to v0.3.0 and I'm not too sure if I'm doing it right. 

Do the newly implemented classes on `backgroundRepeat` and `svg` gets pulled through even if my TW config file is not updated? 

Is it necessary to diff and update our config files with the [new one](https://github.com/tailwindcss/tailwindcss/blob/master/defaultConfig.stub.js) in order to support the new features?

### Edit
I realised that all classes in the modules option are pulled through unless the property is set to false. Good to know, but what about the default settings?

**Comment by adamwathan** [comment]
Any new modules will be added with their default config values if you omit them from your own config 👍 

> Good to know, but what about the default settings?

I'm not sure what your actual question is here, but if you want to see the default settings and copy them into your own config, you can always reference this file:

https://github.com/tailwindcss/tailwindcss/blob/master/defaultConfig.stub.js#L812-L858

By leaving those keys out of your own `modules` property, you are already getting those default values 👍

**Comment by pxwee5** [comment]
Was not completely sure about that in the beginning. 

Thanks for the clarification. I guess the easiest way now is to go check the default configuration during every update to get the new feature configs.
