### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by laurencei** [tailwindcss/discuss#80]
Hi,

Any chance of the https://tailwindcss.com/docs being a repo, so we can submit PR's for changes in the docs?

In this instance can we add something in the installation section "2. Create a Tailwind config file"

like "Windows users not using bin links can run `node ./node_modules/tailwindcss/lib/cli.js init [filename]`

**Comment by MichaelDeBoey** [comment]
The docs are just in the tailwindcss/tailwindcss repo
If you want to add a change to the docs, it's best to check [the contribution notes](https://github.com/tailwindcss/tailwindcss/blob/master/.github/CONTRIBUTING.md#building-the-documentation) I think 🙂

**Comment by laurencei** [comment]
Whoops - didnt see the docs in the main repo. I'll do the PR there. Thanks.
