### ISSUE TITLE
Apply directive not working as expected

### ISSUE THREAD

**Issue by paschaldev** [tailwindcss/discuss#83]
I'm using tailwind with Webpack and I'm having this weird issue. For now, I have two css files, `core.css` and `components/header.css`. These are their contents:

**core.css**
```css
@tailwind preflight;

@tailwind utilities;

@import './components/header.css';
```

**header.css**
```css
header{
    @apply .bg-black;
}
```

When I save and webpack runs, I get this error:

```
ERROR in ./node_modules/css-loader?{"importLoaders":1}!./node_modules/postcss-loader/lib!./src/css/components/header.css
    Module build failed: Syntax Error 
    
    (3:2) `@apply` cannot be used with `.bg-black` because `.bg-black` either cannot be found, or it's actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.bg-black` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.
    
      1 | header{
      2 | 
    > 3 | 	@apply .bg-black;
        | 	^
      4 | }
```

However, if I move the content of `components/header.css` and put directly in `core.css`, everything works perfectly. Like this:

**core.css**

```css
@tailwind preflight;

@tailwind utilities;

header{
    @apply .bg-black;
}
```

**Comment by paschaldev** [comment]
I looked around and installed `postcss-import` Here is my configuration:

**postcsss.config.js**
module.exports = {

	plugins: [
		require('autoprefixer'),
		require('tailwindcss')('./tailwind.js'),
		require('postcss-import')
	]
}

After wwbpack runs, I get these warning.

```
WARNING in ./node_modules/css-loader?{"importLoaders":1}!./node_modules/postcss-loader/lib!./src/css/core.css
(Emitted value instead of an instance of Error) postcss-import: /Users/ezeugwupaschal/Documents/GitHub/ehs-www/src/css/core.css:5:1: @import must precede all other statements (besides @charset)
 @ ./src/css/core.css 4:14-133 18:2-22:4 19:20-139
 @ ./index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./index.js
Child html-webpack-plugin for "index.html":
     1 asset
       [0] ./node_modules/html-loader!./node_modules/ejs-html-loader/lib!./src/templates/index.ejs?title=Index 569 bytes {0} [built]
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--1-2!node_modules/postcss-loader/lib/index.js!src/css/core.css:
       [0] ./node_modules/css-loader?{"importLoaders":1}!./node_modules/postcss-loader/lib!./src/css/core.css 292 kB {0} [built] [1 warning]
       [1] ./node_modules/css-loader/lib/css-base.js 2.26 kB {0} [built]
    
    WARNING in ./node_modules/css-loader?{"importLoaders":1}!./node_modules/postcss-loader/lib!./src/css/core.css
    (Emitted value instead of an instance of Error) postcss-import: /Users/ezeugwupaschal/Documents/GitHub/ehs-www/src/css/core.css:5:1: @import must precede all other statements (besides @charset)
webpack: Compiled with warnings.

```

**Comment by paschaldev** [comment]
UPDATE: The only workaround to this was to move the `@tailwind`directives to a separate css file and import that file first.

**Comment by adamwathan** [comment]
postcss-import should be the very first plugin in your plugin list; it
needs to run before Tailwind in order for the imports to be inlined by the
time Tailwind sees your CSS. Make sure you make that change if you haven’t
already to avoid future issues 👍

Ultimately all of this is just the nature of using CSS without a
preprocessor like Less or Sass. `@import` statements are totally valid in
regular CSS; they tell the browser “fetch this resource using a separate
HTTP request.” postcss-import lets you in-line your imports like a
preprocessor would, but it is very strict about the CSS spec which states
that import statements must come first in a CSS file.

I’ll try and find some time to add documentation around this since it comes
up a lot.

**Comment by paschaldev** [comment]
Yes I noticed that too and made the change (postcss-import as the first plugin in the list). Everythng is working fine now.
