### ISSUE TITLE
Trouble with @apply in a css module

### ISSUE THREAD

**Issue by craigcartmell** [tailwindcss/discuss#87]
Hey,

I have a component css file which is locally scoped using css-modules, but I'd like to use `@apply` to apply a global tailwind class. Unfortunately I'm getting the following error:

> (2:5) `@apply` cannot be used with `.rounded-lg` because `.rounded-lg` either cannot be found, or it's actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.rounded-lg` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

I'm sure this is just something to do with the order in which my css is being imported, but I can't seem to get to the bottom of it. 

I have a feeling extract to text plugin is the only way I can accomplish this? Currently webpack is loading all stylesheets as separate blobs.

Anyway, apologies for the upcoming wall of code.

### /some/component/styles.css

```
.component {
    @apply .rounded-lg;
    margin-bottom: 10px;
    border: 1px solid config('colors.grey');
    border-bottom: 2px solid config('colors.pink-dark');
    background-color: config('colors.white');
}
```

### webpack.config.js

```
{
        test: /\.css$/,
        exclude: path.resolve(__dirname, "node_modules"),
        use: [
          {
            loader: "style-loader",
            options: {
              sourceMap: true,
            }
          },
          {
            loader: "css-loader",
            options: {
              modules: true,
              sourceMap: true,
              importLoaders: 1,
              localIdentName: "[name]-[local][hash:base64:5]",
            },
          },
          {
            loader: "postcss-loader",
          },
        ]
      },
```
### postcss.config.js

```
var nested = require('postcss-nested')
var atImport = require('postcss-import')
var autoprefixer = require('autoprefixer')
var tailwindcss = require('tailwindcss')

module.exports = {
  // ident: "postcss",
  plugins: [
    atImport(),
    tailwindcss('./tailwind.config.js'),
    nested(),
    autoprefixer(),
  ],
  sourceMap: true,
}
```

### stylesheets/bundle.css

```
@import './tailwind-preflight.css';
@import './tailwind-utilities.css';
```

### stylesheets/tailwind-preflight.css
```
:global {
    @tailwind preflight;
}
```

### stylesheets/tailwind-utilities.css
```
:global {
    @tailwind utilities;
}
```

### index.js (my webpack entry file)

```
...
require('./stylesheets/bundle.css')
...
```

**Comment by adamwathan** [comment]
The general issue here is that Tailwind can only `@apply` classes that it can see, so in the context of a CSS Module that is evaluated independently, it can only see other classes in that module.

We'd like to make it possible to apply utilities even if they aren't in the current scope somehow eventually; it's just not a huge priority right now.

Here's another discussion about this:

https://github.com/tailwindcss/tailwindcss/pull/169#issuecomment-343549111

**Comment by craigcartmell** [comment]
Thanks @adamwathan, that makes a lot of sense.

After raising the issue,I'm actually getting by just fine so far using only tailwind classes in my markup.

Happy to close this then.
