### ISSUE TITLE
Consistency with defaults

### ISSUE THREAD

**Issue by laurencei** [tailwindcss/discuss#88]
I'm loving Tailwind. I'm finding I can write alot of design without needing to review the docs - because I can almost guess what I need to write. But I'm starting to notice some inconsistencies.

For example - take `shadow` and `rounded`.

Lets say I have `shadow-lg` applied to an element. Then I decide "hmmm... I want less shadow". So I go to `shadow-md`. Now if I want even less shadow I would think I should do `shadow-sm` - except there is no `shadow-sm` it is actually just `shadow`.

Now take `rounded`. Lets say I have `rounded-lg` applied. Then I decide "hmmm... I want less rounding". So I try `rounded-md` - except that doesnt work. I need to do `rounded` for the `md` equilivant. Then I need to do `rounded-sm` to get the smallest.

I have three thoughts:

- The `default` version of each option should always be the smallest - and then you build up from there
or
- There is always a `sm`, `md`, `lg` etc - but there is *also* a default which is an alias to one of those classes.
or
- There are no `defaults`. You must always be explicit and pick a size. Tailwind says it doesnt impose design ideas - so it kinda seems strange to have a default (even if it is sensible)?

**Comment by adamwathan** [comment]
We tried a few different things here, including removing the whole idea of `defaults`, but it just felt really annoying to have to say `rounded-md` over and over again for the value that was used 90% of the time.

We also tried the aliasing thing but couldn't get comfortable with generating completely redundant/useless extra CSS.

So in the end we opted to make the sizes that were most commonly used in our projects the `default` sizes. It's not perfect and maybe we'll make changes down the road, but ultimately this felt nicest in practice to use.

Of course all three of your options are already possible by customizing your config file, so you have all the freedom in the world to tweak the system to feel most natural to you 👍 

```js
// Default is smallest
borderRadius: {
  'none': '0',
  default: '.125rem',
  'md': '.25rem',
  'lg': '.5rem',
  'full': '9999px',
},

// Default is an alias
borderRadius: {
  default: '.25rem'
  'none': '0',
  'sm': '.125rem',
  'md': '.25rem',
  'lg': '.5rem',
  'full': '9999px',
},

// No defaults
borderRadius: {
  'none': '0',
  'sm': '.125rem',
  'md': '.25rem',
  'lg': '.5rem',
  'full': '9999px',
},
```

**Comment by laurencei** [comment]
Thanks @adamwathan 

> We also tried the aliasing thing but couldn't get comfortable with generating completely redundant/useless extra CSS.

Just on this point; my interpretation of Tailwind is there is almost an expectation/requirement that anyone using Tailwind would use will PurgeCSS or similar as part of the build process. So therefore does having "redudant" extra CSS in the original file matter, since it will be excluded from the production file?

**Comment by adamwathan** [comment]
> my interpretation of Tailwind is there is almost an expectation/requirement that anyone using Tailwind would use will PurgeCSS or similar as part of the build process.

This isn't true; we didn't discover PurgeCSS until Tailwind had already been released. That's why we document so many other ways to control your file size here:

https://tailwindcss.com/docs/controlling-file-size

**Comment by laurencei** [comment]
...so now that you *have* discovered PurgeCSS - does that change the direction of Tailwind at alll?

i.e. you could add lots more classes, whilst simulatenously keeping the file size to a minimum (if you assume peope will Purge it). For example, in your CoinToad demo, it was clear that having more padding sizes (such as 12) would have been useful to you during the demo (for the bottom padding).

Or do you want to keep the overhead low regardless?

_(I dont mind either way - I'm genuinely curious)_

**Comment by adamwathan** [comment]
I think we have to make it possible to keep the file size under control without PurgeCSS no matter what, because there's a lot of gotchas to using Purge that affect how you author your templates, and there's always going to be people who do stuff like store HTML with attached class names in a database and Purge has no way of detecting classes used there.

**Comment by laurencei** [comment]
Ok cool - thanks.
