### ISSUE TITLE
@apply cannot be used with responsive classes?

### ISSUE THREAD

**Issue by sbkl** [tailwindcss/discuss#91]
Hi,

Thank you for the work on tailwind. Great library.

I created a module with responsive classes as follow:

```
.nav-item
    @apply .flex .items-center .py-4 .md:mr-4 .px-6 .border-b .md:border-b-4

.nav-item-not-active
    @apply .hover:text-grey-darkest .md:border-white

.nav-item-active
    @apply .border-orange .text-orange
```

and import it as follow:

```
/**
 * Here you would add any of your custom component classes; stuff that you'd
 * want loaded *before* the utilities so that the utilities could still
 * override them.
 *
 * Example:
 *
 * .btn { ... }
 * .form-input { ... }
 *
 * Or if using a preprocessor or `postcss-import`:
 *
 * @import "components/buttons";
 * @import "components/forms";
 */

@import './components/label.sass'
@import './components/buttons.sass'
@import './components/nav.sass'
```
No issue on the two first components. But I get the following error when compiling with mix for the nav component:

> `@apply` cannot be used with .md\:mr-4 because .md\:mr-4 is nested inside of an at-rule (@media).

Does that mean that we can't use responsive classes with modules? Not a big deal but just wanted to know if there is some kind of trick for this.

Thank you.

**Comment by adamwathan** [comment]
Yeah for more info about this read the documentation:

https://tailwindcss.com/docs/functions-and-directives#apply

**Comment by sbkl** [comment]
thanks
