### ISSUE TITLE
[Question/Request] Custom font setup

### ISSUE THREAD

**Issue by aaronmoodie** [tailwindcss/discuss#93]
The comments in the `config.js` specify that `If you're using custom fonts you'll need to import them prior to defining them here`, but doesn't give an example of where or how these need to be imported. 

Is this just a css `@import`, or do fonts need to be loaded via webpack prior to the `css-loader` ? 

Thanks.

**Comment by aaronmoodie** [comment]
Just a follow up on this. I currently have my custom font added to the tailwind config:
```
fonts: {
    'sans': [
      'Atlas Grotesk',
      '-apple-system',
      ...
     ]
}
```

I've added this to my web pack config:
```
{
  test: /\.(ttf|otf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
  use: [
    {
      loader: 'file-loader?name=fonts/[name].[ext]'
    }
  ]
}
```

and I've added the `@font-face` css to my main `index.css`. The fonts are being included in my CSS, but I'm not seeing the font applied to the body unless I explicitly add `@apply font-sans;` to `body`.

**Comment by suxur** [comment]
Did you solve this?

**Comment by aaronmoodie** [comment]
@suxur Yeah, I did. After adding your custom font  to the `sans` array, you still need to add `@apply .font-sans;` to the body css. It's not applied automatically. 

```css
.body {
  @apply .font-sans;
}
```

**Comment by suxur** [comment]
@aaronmoodie thanks for replying! I figured it our shortly after I asked. I included the custom font from Google Fonts in my head, added it to the `sans` array and then just added the class to my body tag.
