### ISSUE TITLE
Missing profile photo on tailwindcss.com

### ISSUE THREAD

**Issue by citricsquid** [tailwindcss/discuss#95]
When changing a Twitter avatar the old image is removed. @davidhemphill has changed their avatar so their avatar URL is now producing a 404 on [tailwindcss.com](https://tailwindcss.com). I can't find a repository to commit a fix to (is the site opensource somewhere?) so I'm making this issue instead.

To avoid this issue you can either use `https://twitter.com/username/profile_image?size=normal|bigger|mini|original` or a service like [avatars.io](https://avatars.io).

e.g: https://twitter.com/davidhemphill/profile_image?size=original
e.g: https://avatars.io/twitter/davidhemphill

**Comment by MichaelDeBoey** [comment]
Fixed it in tailwindcss/tailwindcss#343 🙂
