### ISSUE TITLE
Space between images with flex wrap (how to get rid of this space)

### ISSUE THREAD

**Issue by alexcsandru** [tailwindcss/discuss#98]
I have a clean tailwindcss install, and when I have a list of images with flex wrap, the wrap make a space between elements.

[Example here : https://jsfiddle.net/dqoqh7z7/](https://jsfiddle.net/dqoqh7z7/)
I cannot understand why there is a space between images. (red space from bg-red)
I want flex-wrap to be without space between images.

Any solution? From where is that space?

Thanks for your time!

**Comment by adamwathan** [comment]
Need to make the images block or inline-block; they are inline by default and therefore affected by line height:

https://jsfiddle.net/dqoqh7z7/1/

**Comment by alexcsandru** [comment]
Yeah!! thanks a lot. 
With .block class on images!

Have a good day! and thanks for your work!
