### ISSUE TITLE
[Question] Responsive video/iframe embed

### ISSUE THREAD

**Issue by jordonbaade** [tailwindcss/discuss#99]
Has anyone put together a responsive video/iframe embed?  I'm working on a project now that requires one and can't seem to get anything to work without setting a fixed height.

**Comment by adamwathan** [comment]
I usually use custom "aspect ratio" utilities for this; the general hack is to use a percentage based padding to determine the containers size, then absolute position the child:

```
.aspect-16x9 {
  padding-bottom: 56.25%; // (9 / 16 = 0.5625)
}
```

Markup would then look like this:

```
<div class="relative aspect-16x9">
  <iframe class="absolute pin">...</iframe>
</div>
```

**Comment by jordonbaade** [comment]
Great, thanks for responding so fast Adam!  Worked perfectly for me with width and height utilities, here's what I landed on: 

![image](https://user-images.githubusercontent.com/840932/34961965-a2f8a65c-fa0f-11e7-9308-182b8ce88e64.png)
